import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const WINDOW_SIZE = 10;
const MIN_DISTINCT_LINES = 7;
const SOURCE_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const STATIC_SVG_COMPONENT_RE = /(?:^|\/)[^/]+(?:_svg|\.svg)\.(?:tsx|jsx|ts|js)$/i;

const MEANINGFUL_LINE = /\S/;

const normaliseLine = (line: string): string =>
	line
		.replace(/"[^"]*"|'[^']*'|`[^`]*`/g, '"L"')
		.replace(/\b\d+(?:\.\d+)?\b/g, "0")
		.replace(/\s+/g, " ")
		.trim();

const isTrivialLine = (line: string): boolean => {
	const trimmed = line.trim();
	if (trimmed.length === 0) return true;
	if (trimmed === "{" || trimmed === "}" || trimmed === "});" || trimmed === "},") return true;
	if (trimmed.startsWith("//")) return true;
	if (trimmed.startsWith("/*") || trimmed.startsWith("*")) return true;
	return false;
};

const SVG_MARKUP_RE =
	/<\/?(?:svg|path|polyline|line|circle|rect|g)\b|(?:xmlns|viewBox|stroke(?:-width|-linecap|-linejoin)?|fill|fill-opacity|d|points|x1|x2|y1|y2)=/;

const DATA_LITERAL_RE =
	/^\s*(?:[A-Za-z_$][\w$-]*:\s*(?:["'`[{]|\d|true\b|false\b|null\b)|["'`][^"'`]*["'`],?\s*$|[{}\]],?\s*$|\),?\s*$)/;

interface BlockHit {
	startLine: number;
	normalised: string[];
}

const SUPPRESS_RE =
	/aislop[- ]ignore(?:-next-block|-file)?\b.*\b(?:duplicate-block|code-quality\/duplicate-block)\b/;

const FILE_SUPPRESS_RE =
	/aislop[- ]ignore-file\b.*\b(?:duplicate-block|code-quality\/duplicate-block)\b/;

const fileHasSuppression = (content: string): boolean => FILE_SUPPRESS_RE.test(content);

const isLowSignalMarkupWindow = (lines: string[]): boolean => {
	const markupLines = lines.filter((line) => SVG_MARKUP_RE.test(line)).length;
	return markupLines >= Math.ceil(WINDOW_SIZE / 2);
};

const isLowSignalDataWindow = (lines: string[]): boolean => {
	const dataLines = lines.filter((line) => DATA_LITERAL_RE.test(line)).length;
	return dataLines >= WINDOW_SIZE - 1;
};

const findSuppressedLines = (lines: string[]): Set<number> => {
	const suppressed = new Set<number>();
	for (let i = 0; i < lines.length; i++) {
		if (!SUPPRESS_RE.test(lines[i])) continue;
		let depth = 0;
		let started = false;
		for (let j = i + 1; j < lines.length; j++) {
			suppressed.add(j + 1);
			const opens = (lines[j].match(/\{/g) ?? []).length;
			const closes = (lines[j].match(/\}/g) ?? []).length;
			depth += opens - closes;
			if (opens > 0) started = true;
			if (started && depth <= 0) break;
		}
	}
	return suppressed;
};

const collectMeaningfulLines = (content: string): BlockHit[] => {
	if (fileHasSuppression(content)) return [];
	const lines = content.split("\n");
	const suppressed = findSuppressedLines(lines);
	const hits: BlockHit[] = [];
	for (let i = 0; i < lines.length - WINDOW_SIZE + 1; i++) {
		if (suppressed.has(i + 1)) continue;
		const window = lines.slice(i, i + WINDOW_SIZE);
		if (window.some((l) => !MEANINGFUL_LINE.test(l))) continue;
		if (isLowSignalMarkupWindow(window)) continue;
		if (isLowSignalDataWindow(window)) continue;
		if (window.every(isTrivialLine)) continue;
		const normalised = window.map(normaliseLine);
		const meaningfulCount = normalised.filter((n) => n.length > 0 && n !== "}" && n !== "{").length;
		if (meaningfulCount < WINDOW_SIZE - 1) continue;
		if (new Set(normalised).size < MIN_DISTINCT_LINES) continue;
		hits.push({ startLine: i + 1, normalised });
	}
	return hits;
};

interface DuplicateGroup {
	priorStart: number;
	priorEnd: number;
	currentStart: number;
	currentEnd: number;
}

const findDuplicateBlocks = (content: string, relativePath: string): Diagnostic[] => {
	const blocks = collectMeaningfulLines(content);
	const seen = new Map<string, number>();
	const reports: DuplicateGroup[] = [];
	const reportedCurrent = new Set<number>();
	for (const block of blocks) {
		const key = block.normalised.join("\n");
		const prior = seen.get(key);
		if (prior === undefined) {
			seen.set(key, block.startLine);
			continue;
		}
		if (block.startLine - prior < WINDOW_SIZE) continue;
		if (reportedCurrent.has(prior)) continue;
		const last = reports[reports.length - 1];
		if (
			last &&
			block.startLine - last.currentStart < WINDOW_SIZE &&
			prior - last.priorStart < WINDOW_SIZE
		) {
			last.priorEnd = Math.max(last.priorEnd, prior + WINDOW_SIZE - 1);
			last.currentEnd = Math.max(last.currentEnd, block.startLine + WINDOW_SIZE - 1);
			continue;
		}
		reportedCurrent.add(prior);
		reports.push({
			priorStart: prior,
			priorEnd: prior + WINDOW_SIZE - 1,
			currentStart: block.startLine,
			currentEnd: block.startLine + WINDOW_SIZE - 1,
		});
	}
	return reports.map((r) => {
		const span = r.currentEnd - r.currentStart + 1;
		return {
			filePath: relativePath,
			engine: "code-quality",
			rule: "code-quality/duplicate-block",
			severity: "warning",
			message: "Duplicate code block — extract a shared helper",
			help: `Pull the shared logic into a function both sites can call. Keeps one version of the truth and makes future changes one-shot instead of N-shot.`,
			line: r.currentStart,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${span} lines duplicate block at L${r.priorStart}`,
		};
	});
};

export const detectDuplicateBlocks = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];
	for (const filePath of files) {
		const ext = path.extname(filePath).toLowerCase();
		if (!SOURCE_EXTS.has(ext)) continue;
		if (filePath.endsWith(".d.ts")) continue;
		if (isAutoGenerated(filePath)) continue;
		const relative = relativePosix(context.rootDirectory, filePath);
		if (STATIC_SVG_COMPONENT_RE.test(relative)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		diagnostics.push(...findDuplicateBlocks(content, relative));
	}
	return diagnostics;
};
