import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const METHOD_CALL_RE = /^\s*\.([A-Za-z_$][\w$]*)\s*\(/;
const CHAIN_THRESHOLD = 5;

const hasOnlyLiteralDifferences = (lines: string[]): boolean => {
	const normalised = lines.map((l) =>
		l
			.replace(/"[^"]*"|'[^']*'|`[^`]*`/g, '"L"')
			.trim()
			.replace(/;\s*$/, ""),
	);
	return new Set(normalised).size === 1;
};

const findRepeatedChains = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");
	let i = 0;
	while (i < lines.length) {
		const match = lines[i].match(METHOD_CALL_RE);
		if (!match) {
			i += 1;
			continue;
		}
		const methodName = match[1];
		const runStart = i;
		let runEnd = i;
		while (runEnd + 1 < lines.length) {
			const next = lines[runEnd + 1].match(METHOD_CALL_RE);
			if (!next || next[1] !== methodName) break;
			runEnd += 1;
		}
		const runLength = runEnd - runStart + 1;
		if (
			runLength >= CHAIN_THRESHOLD &&
			hasOnlyLiteralDifferences(lines.slice(runStart, runEnd + 1))
		) {
			diagnostics.push({
				filePath: relativePath,
				engine: "code-quality",
				rule: "code-quality/repeated-chained-call",
				severity: "warning",
				message: `${runLength} consecutive \`.${methodName}()\` calls that differ only in string literals. Extract a data table + loop.`,
				help: `Move the per-call args into an array and call \`.${methodName}()\` in a \`for\` loop. Keeps the registration in one place and lets you document the table once.`,
				line: runStart + 1,
				column: 0,
				category: "Complexity",
				fixable: false,
			});
			i = runEnd + 1;
		} else {
			i += 1;
		}
	}
	return diagnostics;
};

const SOURCE_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

export const detectRepeatedChainedCalls = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];
	for (const filePath of files) {
		const ext = path.extname(filePath).toLowerCase();
		if (!SOURCE_EXTS.has(ext)) continue;
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relative = relativePosix(context.rootDirectory, filePath);
		diagnostics.push(...findRepeatedChains(content, relative));
	}
	return diagnostics;
};
