import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments } from "../../utils/source-masker.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PY_EXTS = new Set([".py"]);

const THIN_WRAPPER_PATTERNS: Array<{ pattern: RegExp; extensions: Set<string> }> = [
	{
		pattern:
			/(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\([^)]*\)\s*(?::\s*\w[^{]*)?\{\s*\n?\s*return\s+\w+\([^)]*\);\s*\n?\s*\}/g,
		extensions: JS_EXTS,
	},
	{
		pattern:
			/(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s+)?\([^)]*\)\s*(?::\s*\w[^=]*)?\s*=>\s*\w+\([^)]*\);/g,
		extensions: JS_EXTS,
	},
	{
		pattern: /def\s+(\w+)\s*\([^)]*\)(?:\s*->[^:]*)?:\s*\n\s+return\s+\w+\([^)]*\)\s*$/gm,
		extensions: PY_EXTS,
	},
];

// Detect AI naming patterns
const AI_NAMING_PATTERNS = [
	// helper_1, helper_2, etc.
	/(?:helper|util|handler|process|do|handle|execute|perform)_?\d+/i,
	// data1, data2, temp1, etc.
	/(?:data|temp|result|value|item|obj|arr|str|num|val)\d+/,
];

// Python test/framework method names that should not be flagged
const FRAMEWORK_METHOD_NAMES =
	/^(?:setUp|tearDown|setUpClass|tearDownClass|setUpModule|tearDownModule)$/;

const DUNDER_PATTERN = /^__\w+__$/;

const stripParam = (p: string): string =>
	p
		.trim()
		.split(/[:=]/)[0]
		.trim()
		.replace(/^[*&]+/, "");

const paramNames = (paramsText: string): Set<string> =>
	new Set(
		paramsText
			.split(",")
			.map(stripParam)
			.filter((p) => p && p !== "self" && p !== "cls"),
	);

// A thin wrapper forwards its own parameters unchanged. Transforming the args (member access,
// literals, expressions) or forwarding non-parameters is real work, not a passthrough.
const isIdentityForward = (matchText: string): boolean => {
	const paramsMatch = matchText.match(/\(([^)]*)\)/);
	const innerMatch = matchText.match(/(?:return\s+\w+|=>\s*\w+)\s*\(([^)]*)\)/);
	if (!paramsMatch || !innerMatch) return false;
	const params = paramNames(paramsMatch[1]);
	const args = innerMatch[1]
		.split(",")
		.map((a) => a.trim())
		.filter((a) => a.length > 0);
	if (args.length === 0) return false;
	return args.every((a) => /^[A-Za-z_$][\w$]*$/.test(a) && params.has(a));
};

// React useContext wrapper pattern — idiomatic, not slop
const isUseContextWrapper = (matchText: string): boolean =>
	/\buse\w+/.test(matchText) && /useContext\s*\(/.test(matchText);

const detectThinWrappers = (content: string, relativePath: string, ext: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (const { pattern, extensions } of THIN_WRAPPER_PATTERNS) {
		if (!extensions.has(ext)) continue;
		const regex = new RegExp(pattern.source, pattern.flags);
		for (const match of content.matchAll(regex)) {
			const funcName = match[1];
			const matchText = match[0];
			const lineNumber = content.slice(0, match.index).split("\n").length;

			// Skip dunder methods like __init__, __str__, etc.
			if (DUNDER_PATTERN.test(funcName)) continue;

			// Skip Python test/framework method names
			if (FRAMEWORK_METHOD_NAMES.test(funcName)) continue;

			// Skip functions preceded by a decorator (line above starts with @)
			if (lineNumber >= 2) {
				const prevLine = lines[lineNumber - 2]?.trim();
				if (prevLine?.startsWith("@")) continue;
			}

			// Only flag a true passthrough; transforming/forwarding non-params is real work.
			if (!isIdentityForward(matchText)) continue;

			// Skip React useContext wrappers (idiomatic pattern)
			if (isUseContextWrapper(matchText)) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/thin-wrapper",
				severity: "warning",
				message: `Function '${funcName}' is a thin wrapper that only calls another function`,
				help: "Consider calling the inner function directly instead of wrapping it",
				line: lineNumber,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}
	}
	return diagnostics;
};

const detectAiNaming = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");
	for (let i = 0; i < lines.length; i++) {
		const declMatch = lines[i].match(/(?:const|let|var|function|def|func|fn)\s+(\w+)/);
		if (!declMatch) continue;
		const name = declMatch[1];
		const matched = AI_NAMING_PATTERNS.some((pattern) => pattern.test(name));
		if (!matched) continue;
		diagnostics.push({
			filePath: relativePath,
			engine: "ai-slop",
			rule: "ai-slop/generic-naming",
			severity: "info",
			message: `'${name}' uses generic AI-style naming`,
			help: "Use descriptive names that explain what the code does",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return diagnostics;
};

export const detectOverAbstraction = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relativePath = relativePosix(context.rootDirectory, filePath);
		const ext = path.extname(filePath);
		const codeOnly = maskComments(content, ext);
		diagnostics.push(...detectThinWrappers(codeOnly, relativePath, ext));
		diagnostics.push(...detectAiNaming(codeOnly, relativePath));
	}

	return diagnostics;
};
