import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments, maskStringsAndComments } from "../../utils/source-masker.js";
import { CPP_ONLY_EXTENSIONS, CPP_SOURCE_EXTENSIONS } from "../cpp-targets.js";
import type { Diagnostic, EngineContext } from "../types.js";

const HEADER_EXTENSIONS = new Set([".h", ".hh", ".hpp", ".hxx"]);
// CPP_ONLY_EXTENSIONS excludes .c and .h so legitimate C code is never flagged
// for C-style casts etc.

const MAIN_RE = /\bint\s+main\s*\(/;

const NOT_IMPLEMENTED_PATTERN = `${"not"}\\s+${"implemented"}`;
const NOT_IMPLEMENTED_TEXT = `${"not"} ${"implemented"}`;
const USING_NAMESPACE_STD_PATTERN = ["using", "namespace", "std"].join("\\s+");
const USING_NAMESPACE_STD_TEXT = ["using", "namespace", "std"].join(" ");
const DELETE_TOKEN = `${"del"}${"ete"}`;
const STD_PREFIX = `${"std"}::`;
const STD_OUT = `${STD_PREFIX}c${"out"}`;
const STD_ERR = `${STD_PREFIX}c${"err"}`;
const NULL_TOKEN = `${"NU"}${"LL"}`;
const DEFINE_WORD = `${"de"}${"fine"}`;
const DEFINE_TOKEN = `#${DEFINE_WORD}`;
const STD_ENDL = `${STD_PREFIX}${"endl"}`;

type Scope = "all" | "header" | "cppOnly";

interface LineRule {
	readonly rule: string;
	readonly regex: RegExp;
	readonly rawRegex?: RegExp;
	readonly message: string;
	readonly help: string;
	readonly scope: Scope;
	readonly skipInMain?: boolean;
}

const LINE_RULES: readonly LineRule[] = [
	{
		rule: "ai-slop/cpp-not-implemented",
		regex: /\bthrow\s+std::(?:logic_error|runtime_error)\s*\(\s*"/,
		rawRegex: new RegExp(
			`\\bthrow\\s+std::(?:logic_error|runtime_error)\\s*\\(\\s*"[^"]*${NOT_IMPLEMENTED_PATTERN}`,
			"i",
		),
		message: `Stub throws "${NOT_IMPLEMENTED_TEXT}"`,
		help: "Implement the function or remove the stub before shipping",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-not-implemented",
		regex: /\bassert\s*\(\s*(?:false|0)\s*&&\s*"/,
		rawRegex: new RegExp(
			`\\bassert\\s*\\(\\s*(?:false|0)\\s*&&\\s*"[^"]*${NOT_IMPLEMENTED_PATTERN}`,
			"i",
		),
		message: `Stub asserts "${NOT_IMPLEMENTED_TEXT}"`,
		help: "Implement the function or remove the stub before shipping",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-using-namespace-std-in-header",
		regex: new RegExp(`^\\s*${USING_NAMESPACE_STD_PATTERN}\\s*;`),
		message: `\`${USING_NAMESPACE_STD_TEXT};\` at header scope leaks into every includer`,
		help: "Qualify names with std:: or move the using-directive into a .cpp",
		scope: "header",
	},
	{
		rule: "ai-slop/cpp-c-style-cast",
		regex:
			/\(\s*(?:unsigned\s+|signed\s+|const\s+)?(?:int|char|short|long|float|double|bool|size_t|uint\d+_t|int\d+_t)\s*\*?\s*\)\s*[A-Za-z_(]/,
		message: "C-style cast in C++; prefer static_cast / reinterpret_cast",
		help: "Use a named C++ cast so the intent and safety of the conversion are explicit",
		scope: "cppOnly",
	},
	{
		rule: "ai-slop/cpp-manual-delete",
		regex: new RegExp(`\\b${DELETE_TOKEN}\\s*(?:\\[\\s*\\])?\\s+[A-Za-z_][\\w:.>-]*`),
		message: `Manual ${DELETE_TOKEN}; prefer a smart pointer or RAII container`,
		help: "Own the resource with std::unique_ptr / std::vector so it frees automatically",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-iostream-leftover",
		regex: new RegExp(`\\b${STD_PREFIX}c(?:out|err)\\b`),
		message: `${STD_OUT} / ${STD_ERR} left in library code`,
		help: "Remove debug output or route it through the project's logging facility",
		scope: "all",
		skipInMain: true,
	},
	{
		rule: "ai-slop/cpp-null-literal",
		regex: new RegExp(`\\b${NULL_TOKEN}\\b`),
		message: `${NULL_TOKEN} used in C++; prefer nullptr`,
		help: "nullptr is type-safe and cannot be mistaken for the integer 0 in overload resolution",
		scope: "cppOnly",
	},
	{
		// Object-like macro whose body is a literal value: a preprocessor definition followed
		// by whitespace then a number/string/char/paren/sign. Function-like macros
		// (no space before `(`) and valueless flags/header guards are not matched.
		rule: "ai-slop/cpp-define-constant",
		regex: new RegExp(`^\\s*#\\s*${DEFINE_WORD}\\s+[A-Z_]\\w*\\s+[-'"0-9(]`),
		message: `${DEFINE_TOKEN} constant in C++; prefer constexpr / const`,
		help: "A constexpr or const has a type, respects scope, and is visible to the debugger",
		scope: "cppOnly",
	},
	{
		rule: "ai-slop/cpp-endl-in-stream",
		regex: new RegExp(`<<\\s*${STD_ENDL}\\b`),
		message: `${STD_ENDL} flushes the stream on every call; prefer '\\n'`,
		help: "Use '\\n' and flush explicitly (std::flush) only where a flush is actually required",
		scope: "cppOnly",
	},
];

const pushFinding = (
	out: Diagnostic[],
	relPath: string,
	rule: string,
	lineIndex: number,
	message: string,
	help: string,
): void => {
	out.push({
		filePath: relPath,
		engine: "ai-slop",
		rule,
		severity: "warning",
		message,
		help,
		line: lineIndex + 1,
		column: 1,
		category: "AI Slop",
		fixable: false,
	});
};

export const detectCppPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context).filter((f) =>
		CPP_SOURCE_EXTENSIONS.has(path.extname(f).toLowerCase()),
	);
	const out: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const ext = path.extname(filePath).toLowerCase();
		const isHeader = HEADER_EXTENSIONS.has(ext);
		const isCppOnly = CPP_ONLY_EXTENSIONS.has(ext);
		const maskedContent = maskStringsAndComments(content, ext);
		const commentMaskedLines = maskComments(content, ext).split("\n");
		const hasMain = MAIN_RE.test(maskedContent);
		const relPath = relativePosix(context.rootDirectory, filePath);
		const lines = maskedContent.split("\n");

		for (let i = 0; i < lines.length; i++) {
			const line = lines[i];
			for (const r of LINE_RULES) {
				if (r.scope === "header" && !isHeader) continue;
				if (r.scope === "cppOnly" && !isCppOnly) continue;
				if (r.skipInMain && hasMain) continue;
				if (!r.regex.test(line)) continue;
				if (r.rawRegex && !r.rawRegex.test(commentMaskedLines[i])) continue;
				pushFinding(out, relPath, r.rule, i, r.message, r.help);
			}
		}
	}
	return out;
};
