import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskStringsAndComments } from "../../utils/source-masker.js";
import { buildOutputTypeResolver, type OutputTypeResolver } from "../dotnet-output-type.js";
import type { Diagnostic, EngineContext } from "../types.js";
import {
	flagBroadCatch,
	flagIfLadder,
	flagIndexLoop,
	flagLinqCount,
	flagStringConcatInLoop,
} from "./csharp-idioms.js";
import {
	buildCatchWindow,
	CATCH_ONLY_THROW_RE,
	type CSharpSourceLines,
	LINE_COMMENT_RE,
	pushFinding,
	scanLineMatches,
} from "./csharp-shared.js";
import { isNonProductionPath } from "./non-production-paths.js";

const CSHARP_EXTENSIONS = new Set([".cs"]);

const NOT_IMPLEMENTED_RE = /\bthrow\s+new\s+NotImplementedException\s*\(/;

const ASYNC_VOID_RE = /\basync\s+void\s+(\w+)\s*\(/;
// Event-handler shapes that legitimately use async void.
const EVENT_HANDLER_NAME_RE = /^(?:On[A-Z]|.*Handler$|.*_\w+$)/;
const EVENT_ARGS_RE = /\bEventArgs\b/;

const SYNC_OVER_ASYNC_RE =
	/\.(?:Result\b|Wait\s*\(\s*\)|GetAwaiter\s*\(\s*\)\s*\.\s*GetResult\s*\(\s*\))/;

const SYNC_INTENT_LOOKBACK = 2;

// XML-doc summaries that merely restate the member: "Gets/Sets the X", "The X.", etc.
const TRIVIAL_SUMMARY_RE = /^(?:gets?(?:\s+or\s+sets?)?|sets?|the|a|an)\b[\w\s]*\.?$/i;
const EXPLANATORY_KEYWORDS_RE =
	/\b(?:because|since|so that|note|todo|fixme|hack|warn|caveat|important|assumes?|e\.g\.|i\.e\.|when|unless|must|avoid)\b/i;
const SUMMARY_INLINE_RE = /<summary>\s*(.*?)\s*<\/summary>/i;

const hasIntentComment = (lines: readonly string[], lineIndex: number): boolean => {
	for (let j = lineIndex - 1; j >= Math.max(0, lineIndex - SYNC_INTENT_LOOKBACK); j--) {
		if (LINE_COMMENT_RE.test(lines[j])) return true;
	}
	return false;
};

// Extract the text of a single-line `/// <summary>...</summary>`, else null.
const inlineSummaryText = (line: string): string | null => {
	const trimmed = line.trim();
	if (!trimmed.startsWith("///")) return null;
	const match = SUMMARY_INLINE_RE.exec(trimmed);
	return match ? match[1].trim() : null;
};

// Redundant XML-doc lives on `///` lines, which scanLineMatches would skip as
// comments, so it gets its own pass.
const flagRedundantDoc = (lines: readonly string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const summary = inlineSummaryText(lines[i]);
		if (summary === null || summary.length === 0) continue;
		if (EXPLANATORY_KEYWORDS_RE.test(summary)) continue;
		if (!TRIVIAL_SUMMARY_RE.test(summary)) continue;
		pushFinding(
			out,
			relPath,
			"ai-slop/csharp-redundant-doc-comment",
			i,
			"XML-doc summary restates the member name without adding information.",
			'Delete the doc comment, or replace boilerplate ("Gets or sets the X") with the *why*: constraints, units, invariants a reader can\'t infer from the signature.',
		);
	}
};

const PRAGMA_DISABLE_RE = /#pragma\s+warning\s+disable\b/;
const PRAGMA_RESTORE_RE = /#pragma\s+warning\s+restore\b/;
const SUPPRESS_MESSAGE_RE = /\bSuppressMessage\s*\(/;
const JUSTIFICATION_RE = /Justification\s*=\s*"([^"]*)"/i;
// Justifications the IDE/agents auto-insert that carry no real reason.
const PLACEHOLDER_JUSTIFICATION_RE = /^(?:<pending>|pending|todo|)$/i;

// True when a `//` comment exists anywhere on the line (trailing justification).
const hasTrailingComment = (line: string): boolean => line.includes("//");

// True when the nearest non-blank line above is a `//` comment (preceding justification).
const precededByComment = (lines: readonly string[], lineIndex: number): boolean => {
	for (let j = lineIndex - 1; j >= 0; j--) {
		const trimmed = lines[j].trim();
		if (trimmed === "") continue;
		return trimmed.startsWith("//");
	}
	return false;
};

// Suppressing a warning without saying why is the canonical move to make a
// finding vanish - no analyzer can flag its own suppression.
const flagSuppressedWarnings = (
	source: CSharpSourceLines,
	relPath: string,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < source.code.length; i++) {
		const line = source.code[i];
		const rawLine = source.raw[i];
		const trimmed = line.trim();
		if (trimmed.startsWith("//")) continue;

		if (PRAGMA_DISABLE_RE.test(line) && !PRAGMA_RESTORE_RE.test(line)) {
			if (hasTrailingComment(rawLine) || precededByComment(source.raw, i)) continue;
			pushFinding(
				out,
				relPath,
				"ai-slop/csharp-suppressed-warning",
				i,
				"`#pragma warning disable` suppresses the warning without saying why.",
				"Fix the underlying warning. If suppression is genuinely justified, add a `//` comment naming the reason (and prefer a scoped disable/restore over a file-wide one).",
			);
			continue;
		}

		if (SUPPRESS_MESSAGE_RE.test(line)) {
			const match = JUSTIFICATION_RE.exec(rawLine);
			const justified = match !== null && !PLACEHOLDER_JUSTIFICATION_RE.test(match[1].trim());
			if (justified) continue;
			pushFinding(
				out,
				relPath,
				"ai-slop/csharp-suppressed-warning",
				i,
				"`[SuppressMessage]` has no real Justification - it hides the analyzer finding.",
				"Fix the underlying issue, or fill Justification with the actual reason the suppression is safe (not the `<Pending>` placeholder).",
			);
		}
	}
};

// `catch (...) { throw; }` catches and immediately rethrows - pure noise.
const flagEmptyCatchRethrow = (
	lines: readonly string[],
	relPath: string,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		if (lines[i].trim().startsWith("//")) continue;
		if (!/\bcatch\b/.test(lines[i])) continue;
		const window = buildCatchWindow(lines, i);
		if (!CATCH_ONLY_THROW_RE.test(window)) continue;
		pushFinding(
			out,
			relPath,
			"ai-slop/csharp-empty-catch-rethrow",
			i,
			"`catch (...) { throw; }` catches and immediately rethrows - it does nothing but add noise.",
			"Remove the try/catch if you're not handling the exception; use `finally` for cleanup, or `throw new ...(..., ex)` to add context.",
		);
	}
};

// The null-forgiving operator: a postfix `!` on an expression (identifier, `)`,
// or `]`) followed by `.`/`;`/`,`/`)`/`]`/`}`/whitespace/EOL. The required
// following char set excludes `=`, so `!=` never matches; requiring an
// identifier/`)`/`]` immediately before excludes prefix `!x` and `!!`. `!` inside
// a string usually precedes `"` (not in the follow set), so `"done!"` is excluded.
// Deferred / known limitation: Entity-Framework `= null!` and use-site `!` right
// after a manual null check are legitimate but still flag here (high-recall by
// decision); proper carve-outs await a contributor who uses those patterns.
const NULL_FORGIVING_RE = /[\w)\]]!(?=[\s.;,)\]}]|$)/;

// Null-forgiving `!` silences the nullable warning without proving non-null.
const flagNullForgiving = (lines: readonly string[], relPath: string, out: Diagnostic[]): void => {
	scanLineMatches(
		lines,
		relPath,
		out,
		NULL_FORGIVING_RE,
		"ai-slop/csharp-null-forgiving",
		"The null-forgiving `!` silences the nullable warning without proving the value is non-null.",
		"Handle the null case (guard, `??`, or throw with context) instead of asserting non-null. Use `!` only when non-null is provable, and say why.",
	);
};

const DEBUG_TRACE_RE = /\b(?:Debug|Trace)\.(?:Write|WriteLine|WriteIf|WriteLineIf)\s*\(/;
const CONSOLE_OUT_RE = /\bConsole\.(?:Write|WriteLine)\s*\(/;
// Writing to stderr is deliberate status output (the C# `console.error`), never flagged.
const CONSOLE_ERROR_RE = /\bConsole\.Error\b/;

// A file-level `// aislop-worker` comment marks a child-process worker whose
// stdout IS its IPC protocol (the parent reads results from stdout). It exempts
// ONLY the Console.Write* (stdout) scan; Debug/Trace output stays flagged because
// those are still leftovers, not part of the contract.
const WORKER_MARKER_RE = /^\s*\/\/\s*aislop-worker\b/;
const isWorkerFile = (lines: readonly string[]): boolean =>
	lines.some((line) => WORKER_MARKER_RE.test(line));

interface ConsoleScanInput {
	readonly source: CSharpSourceLines;
	readonly relPath: string;
	readonly absolutePath: string;
	readonly outputTypes: OutputTypeResolver;
}

// Debug/Trace output is flagged everywhere (minus non-production paths). `Console.*`
// stdout writes are flagged only in library projects - in an Exe (console app)
// stdout IS the product. `Console.Error.*` (stderr) is always intentional. Mirrors
// the JS console-leftover heuristic in dead-patterns.ts.
const flagConsoleLeftover = (input: ConsoleScanInput, out: Diagnostic[]): void => {
	const { source, relPath, absolutePath, outputTypes } = input;
	if (isNonProductionPath(relPath)) return;

	scanLineMatches(
		source.code,
		relPath,
		out,
		DEBUG_TRACE_RE,
		"ai-slop/csharp-console-leftover",
		"Debug/Trace output left in shipped code is usually a leftover.",
		"Remove the diagnostic write, or route it through the project's logger.",
	);

	if (outputTypes.isExeProject(absolutePath)) return;
	// An IPC worker's stdout is its protocol, not a leftover - skip the Console scan.
	if (isWorkerFile(source.raw)) return;
	scanLineMatches(
		source.code,
		relPath,
		out,
		CONSOLE_OUT_RE,
		"ai-slop/csharp-console-leftover",
		"`Console.Write*` in a library writes to stdout - almost always a leftover.",
		"Remove it or route through the project's logger. (In a console app, or a file marked `// aislop-worker`, this rule doesn't fire.)",
		(_match, i) => !CONSOLE_ERROR_RE.test(source.code[i]),
	);
};

export const detectCSharpPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);
	const outputTypes = buildOutputTypeResolver(context.rootDirectory);

	for (const filePath of files) {
		if (!CSHARP_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = relativePosix(context.rootDirectory, filePath);
		const source: CSharpSourceLines = {
			code: maskStringsAndComments(content, ".cs").split("\n"),
			raw: content.split("\n"),
		};

		scanLineMatches(
			source.code,
			relPath,
			diagnostics,
			NOT_IMPLEMENTED_RE,
			"ai-slop/csharp-not-implemented",
			"`throw new NotImplementedException()` is almost certainly a stub the agent forgot to fill in.",
			"Implement the method, or if the work is genuinely deferred, file a ticket and reference it in a comment so it doesn't ship invisibly.",
		);

		scanLineMatches(
			source.code,
			relPath,
			diagnostics,
			ASYNC_VOID_RE,
			"ai-slop/csharp-async-void",
			"`async void` can't be awaited and its exceptions crash the process. Use `async Task` unless this is an event handler.",
			"Return `Task` so callers can await and observe exceptions. If it must be `void` (event handler), name it accordingly and guarantee it can't throw.",
			(match, i) => !EVENT_HANDLER_NAME_RE.test(match[1]) && !EVENT_ARGS_RE.test(source.code[i]),
		);

		scanLineMatches(
			source.code,
			relPath,
			diagnostics,
			SYNC_OVER_ASYNC_RE,
			"ai-slop/csharp-sync-over-async",
			"Blocking on a Task with `.Result`/`.Wait()`/`.GetAwaiter().GetResult()` risks deadlock and burns a thread.",
			"`await` the task instead. If you genuinely have a completed task and must block, add a short comment naming the invariant so this isn't read as accidental sync-over-async.",
			(_match, i) => !hasIntentComment(source.raw, i),
		);

		flagRedundantDoc(source.raw, relPath, diagnostics);
		flagSuppressedWarnings(source, relPath, diagnostics);
		flagEmptyCatchRethrow(source.code, relPath, diagnostics);
		flagNullForgiving(source.code, relPath, diagnostics);
		flagConsoleLeftover({ source, relPath, absolutePath: filePath, outputTypes }, diagnostics);
		flagBroadCatch(source, relPath, diagnostics);
		flagLinqCount(source.code, relPath, diagnostics);
		flagIndexLoop(source.code, relPath, diagnostics);
		flagIfLadder(source.code, relPath, diagnostics);
		flagStringConcatInLoop(source, relPath, diagnostics);
	}

	return diagnostics;
};
