// aislop-ignore-file duplicate-block
import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments } from "../../utils/source-masker.js";
import { CPP_SOURCE_EXTENSIONS } from "../cpp-targets.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { detectConsoleLeftovers } from "./dead-pattern-console.js";
import { slop } from "./dead-pattern-diagnostic.js";
import { JS_EXTENSIONS } from "./dead-pattern-languages.js";
import { detectUnsafeTypePatterns } from "./dead-pattern-unsafe.js";

// Brace languages where "code after return/throw is unreachable" applies. The
// control-flow guards (if/else/for/while, block closers) are shared C-family
// syntax, so the JS check extends cleanly to C#.
const BRACE_EXTENSIONS = new Set([...JS_EXTENSIONS, ".cs", ...CPP_SOURCE_EXTENSIONS]);

// Brace languages that also carry a C-family preprocessor. A conditional
// directive here marks the start of a different compilation branch, so it
// must not be treated as ordinary code following a return/throw. Excludes
// JS_EXTENSIONS: JS/TS have no preprocessor, and `#` there is a legal prefix
// for private class fields (e.g. `#else` could be a member name).
const PREPROCESSOR_EXTENSIONS = new Set([".cs", ...CPP_SOURCE_EXTENSIONS]);
const PREPROCESSOR_DIRECTIVE_PATTERN = /^#\s*(?:if|ifdef|ifndef|elif|else|endif)\b/;

const todoKeywords = ["TO" + "DO", "FIX" + "ME", "HA" + "CK", "XX" + "X"];
const markerKeywords = ["TE" + "MP", "PLACEHO" + "LDER", "ST" + "UB"];
const TODO_PATTERN = new RegExp(
	`\\b(?:${todoKeywords.join("|")})\\b[:\\s]|\\b(?:${markerKeywords.join("|")})[:\\s]`,
);
const TODO_TRACKING_RE =
	/https?:\/\/|#\d+|\bgh-\d+\b|\b[A-Z][A-Z0-9]+-\d+\b|\b(?:issue|ticket|jira)\b/i;

const isBlockCloserAfterReturn = (line: string): boolean =>
	line.startsWith("}") ||
	line.startsWith("};") ||
	line.startsWith("),") ||
	line.startsWith(");") ||
	line.startsWith("],") ||
	line.startsWith("]);");

const isPreprocessorAlternativeBranch = (nextLine: string, ext: string): boolean =>
	PREPROCESSOR_EXTENSIONS.has(ext) && PREPROCESSOR_DIRECTIVE_PATTERN.test(nextLine);

// A bare `else` (no opening brace) is always the start of an unbraced
// single-statement body. When one directly precedes an exit statement, that
// statement is conditional regardless of what its paired `if` looked like,
// so there's no need to walk further back to find it. This is the
// brace-less style LLVM/Google C++ mandates:
//   if (cond)
//     doWork();
//   else
//     return false;   <- conditional, guarded by the `else` above
//   next();           <- reachable via the `if` branch, not dead code
//
// A bare `do`, in contrast, is NOT a guard: a do-body always runs at least
// once, so an exit statement directly under an unbraced `do` executes
// unconditionally, and code following the loop is genuinely unreachable:
//   do
//     return 1;
//   while (cond);
//   next();           <- unreachable; the do-body always returns first
const BARE_ELSE_PATTERN = /^else\s*$/;
const isGuardedSingleLineExit = (lines: string[], lineIndex: number): boolean => {
	const contextLines: string[] = [];
	for (let i = lineIndex - 1; i >= 0 && contextLines.length < 16; i--) {
		const trimmed = lines[i].trim();
		if (!trimmed || trimmed.startsWith("//")) continue;
		if (BARE_ELSE_PATTERN.test(trimmed)) return true;
		contextLines.unshift(trimmed);
		if (/^(?:if|else\s+if|for|while|foreach)\b/.test(trimmed) || /^}\s*else\s+if\b/.test(trimmed)) {
			break;
		}
		if (/;\s*$/.test(trimmed)) break;
	}

	const control = contextLines.join(" ");
	return (
		/(?:^|[}\s])(?:if|else\s+if|for|while|foreach)\s*\(/.test(control) && !/{\s*$/.test(control)
	);
};

const isPropertyNoopAssignment = (trimmed: string): boolean =>
	/^(?:[\w$]+\.)+[\w$]+\s*=\s*(?:function\s*)?\([^)]*\)\s*(?:=>)?\s*\{\s*\}\s*;?$/.test(trimmed);

const detectTodoStubs = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		if (
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("#") &&
			!trimmed.startsWith("*") &&
			!trimmed.startsWith("/*")
		) {
			continue;
		}

		if (TODO_PATTERN.test(trimmed)) {
			// An item that references a tracking issue is documented debt, not an unfinished stub.
			if (TODO_TRACKING_RE.test(trimmed)) continue;
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/todo-stub",
					"info",
					"Unresolved TODO/FIXME/HACK comment indicates incomplete code",
					"Resolve the TODO or create a tracked issue for it",
					false,
				),
			);
		}
	}

	return diagnostics;
};

const detectDeadCodePatterns = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		const nextLine = i + 1 < lines.length ? lines[i + 1]?.trim() : undefined;

		// Unreachable code after return/throw — but not before }, //, /*, case, default, if, else
		if (
			BRACE_EXTENSIONS.has(ext) &&
			/^(?:return|throw)\b/.test(trimmed) &&
			trimmed.endsWith(";") &&
			nextLine &&
			nextLine.length > 0 &&
			!isGuardedSingleLineExit(lines, i) &&
			!isBlockCloserAfterReturn(nextLine) &&
			!isPreprocessorAlternativeBranch(nextLine, ext) &&
			!nextLine.startsWith("//") &&
			!nextLine.startsWith("/*") &&
			!nextLine.startsWith("case ") &&
			!nextLine.startsWith("default:") &&
			!nextLine.startsWith("if ") &&
			!nextLine.startsWith("if(") &&
			!nextLine.startsWith("else")
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 2,
					"ai-slop/unreachable-code",
					"warning",
					"Code after return/throw statement is unreachable",
					"Remove the unreachable code or restructure the control flow",
					false,
				),
			);
		}

		// Constant conditions — but skip lines that are inside strings or regex patterns
		if (
			/\bif\s*\(\s*(?:false|true|0|1)\s*\)/.test(trimmed) &&
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("*") &&
			!/["'`].*\bif\s*\(/.test(trimmed) &&
			!/\/.*\bif\s*\(/.test(trimmed.replace(/\/\/.*$/, ""))
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/constant-condition",
					"warning",
					"Conditional with a constant value — likely debugging leftover",
					"Remove the constant condition or replace with proper logic",
					false,
				),
			);
		}

		if (
			JS_EXTENSIONS.has(ext) &&
			/(?:function\s+\w+\s*\([^)]*\)|=>\s*)\s*\{\s*\}\s*;?\s*$/.test(trimmed) &&
			!trimmed.startsWith("interface") &&
			!trimmed.startsWith("type ") &&
			!isPropertyNoopAssignment(trimmed)
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/empty-function",
					"info",
					"Empty function body — possible stub or unfinished implementation",
					"Implement the function body or add a comment explaining why it's empty",
					false,
				),
			);
		}
	}

	return diagnostics;
};

// Build regex patterns with concatenation to avoid self-detection
export const detectDeadPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const ext = path.extname(filePath);
		const relativePath = relativePosix(context.rootDirectory, filePath);
		const codeOnly = maskComments(content, ext);

		diagnostics.push(...detectConsoleLeftovers(codeOnly, relativePath, ext));
		diagnostics.push(...detectTodoStubs(content, relativePath));
		diagnostics.push(...detectDeadCodePatterns(codeOnly, relativePath, ext));
		// TypeScript suppression directives live in comments, so this one reads raw.
		diagnostics.push(...detectUnsafeTypePatterns(content, relativePath, ext));
	}

	return diagnostics;
};
