import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JS_TS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const TS_EXTENSIONS = new Set([".ts", ".tsx"]);

type PrimitiveKind = "string" | "number" | "boolean";
type FunctionNode =
	| ts.FunctionDeclaration
	| ts.FunctionExpression
	| ts.ArrowFunction
	| ts.MethodDeclaration
	| ts.ConstructorDeclaration
	| ts.GetAccessorDeclaration
	| ts.SetAccessorDeclaration;

interface ParsedSource {
	sourceFile: ts.SourceFile;
	relativePath: string;
	ext: string;
}

interface ExportedTypeDeclaration {
	name: string;
	signature: string;
	filePath: string;
	line: number;
}

const COERCION_CTORS: Record<PrimitiveKind, string> = {
	string: "String",
	number: "Number",
	boolean: "Boolean",
};

const scriptKindFor = (ext: string): ts.ScriptKind => {
	switch (ext) {
		case ".tsx":
			return ts.ScriptKind.TSX;
		case ".jsx":
			return ts.ScriptKind.JSX;
		case ".js":
		case ".mjs":
		case ".cjs":
			return ts.ScriptKind.JS;
		default:
			return ts.ScriptKind.TS;
	}
};

const lineFor = (sourceFile: ts.SourceFile, node: ts.Node): number =>
	sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1;

const makeDiagnostic = (
	filePath: string,
	line: number,
	rule: string,
	message: string,
	help: string,
): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule,
	severity: "warning",
	message,
	help,
	line,
	column: 0,
	category: "AI Slop",
	fixable: false,
});

const isFunctionNode = (node: ts.Node): node is FunctionNode =>
	ts.isFunctionDeclaration(node) ||
	ts.isFunctionExpression(node) ||
	ts.isArrowFunction(node) ||
	ts.isMethodDeclaration(node) ||
	ts.isConstructorDeclaration(node) ||
	ts.isGetAccessorDeclaration(node) ||
	ts.isSetAccessorDeclaration(node);

const primitiveKindOf = (node: ts.TypeNode | undefined): PrimitiveKind | null => {
	if (!node) return null;
	switch (node.kind) {
		case ts.SyntaxKind.StringKeyword:
			return "string";
		case ts.SyntaxKind.NumberKeyword:
			return "number";
		case ts.SyntaxKind.BooleanKeyword:
			return "boolean";
		default:
			return null;
	}
};

const hasExportModifier = (node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration): boolean =>
	node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false;

const primitiveParamsOf = (node: FunctionNode): Map<string, PrimitiveKind> => {
	const params = new Map<string, PrimitiveKind>();
	for (const param of node.parameters) {
		if (!ts.isIdentifier(param.name)) continue;
		const kind = primitiveKindOf(param.type);
		if (!kind) continue;
		params.set(param.name.text, kind);
	}
	return params;
};

const isRethrowStatement = (statement: ts.Statement, errorName: string): boolean =>
	ts.isThrowStatement(statement) &&
	statement.expression !== undefined &&
	ts.isIdentifier(statement.expression) &&
	statement.expression.text === errorName;

const isPromiseRejectRethrow = (statement: ts.Statement, errorName: string): boolean => {
	if (!ts.isReturnStatement(statement) || !statement.expression) return false;
	const expression = statement.expression;
	if (!ts.isCallExpression(expression) || expression.arguments.length !== 1) return false;
	const [arg] = expression.arguments;
	if (!ts.isIdentifier(arg) || arg.text !== errorName) return false;
	if (!ts.isPropertyAccessExpression(expression.expression)) return false;
	const target = expression.expression;
	return (
		ts.isIdentifier(target.expression) &&
		target.expression.text === "Promise" &&
		target.name.text === "reject"
	);
};

const detectRedundantTryCatch = (sourceFile: ts.SourceFile, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];

	const visit = (node: ts.Node): void => {
		if (ts.isTryStatement(node) && node.catchClause && !node.finallyBlock) {
			const catchNameNode = node.catchClause.variableDeclaration?.name;
			const [onlyStatement] = node.catchClause.block.statements;
			if (
				catchNameNode &&
				ts.isIdentifier(catchNameNode) &&
				node.catchClause.block.statements.length === 1 &&
				onlyStatement &&
				(isRethrowStatement(onlyStatement, catchNameNode.text) ||
					isPromiseRejectRethrow(onlyStatement, catchNameNode.text))
			) {
				diagnostics.push(
					makeDiagnostic(
						relativePath,
						lineFor(sourceFile, node.catchClause),
						"ai-slop/redundant-try-catch",
						"Catch block only rethrows the same error",
						"Remove the try/catch or add useful context, cleanup, or recovery. Rethrowing unchanged errors is usually defensive agent noise.",
					),
				);
			}
		}

		ts.forEachChild(node, visit);
	};

	visit(sourceFile);
	return diagnostics;
};

const detectPrimitiveCoercions = (
	sourceFile: ts.SourceFile,
	relativePath: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];

	const scanFunctionBody = (node: FunctionNode, params: Map<string, PrimitiveKind>): void => {
		const body = node.body;
		if (!body || params.size === 0) return;

		const visitBody = (child: ts.Node): void => {
			if (child !== body && isFunctionNode(child)) return;

			if (ts.isCallExpression(child) && ts.isIdentifier(child.expression)) {
				const [arg] = child.arguments;
				if (arg && ts.isIdentifier(arg)) {
					const primitive = params.get(arg.text);
					if (primitive && child.expression.text === COERCION_CTORS[primitive]) {
						diagnostics.push(
							makeDiagnostic(
								relativePath,
								lineFor(sourceFile, child),
								"ai-slop/redundant-type-coercion",
								`Parameter '${arg.text}' is already typed as ${primitive} but is coerced again`,
								"Trust the typed boundary or validate unknown input before this function. Re-coercing already typed parameters is usually defensive agent noise.",
							),
						);
					}
				}
			}

			ts.forEachChild(child, visitBody);
		};

		visitBody(body);
	};

	const visit = (node: ts.Node): void => {
		if (isFunctionNode(node)) {
			scanFunctionBody(node, primitiveParamsOf(node));
		}
		ts.forEachChild(node, visit);
	};

	visit(sourceFile);
	return diagnostics;
};

const normalizedTypeDeclaration = (
	sourceFile: ts.SourceFile,
	node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration,
): string =>
	sourceFile.text
		.slice(node.getStart(sourceFile), node.getEnd())
		.replace(/\bexport\b/g, "")
		.replace(/\bdeclare\b/g, "")
		.replace(/\s+/g, " ")
		.trim();

const exportedTypesOf = (parsed: ParsedSource): ExportedTypeDeclaration[] => {
	const declarations: ExportedTypeDeclaration[] = [];

	const visit = (node: ts.Node): void => {
		if (
			(ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) &&
			hasExportModifier(node)
		) {
			declarations.push({
				name: node.name.text,
				signature: normalizedTypeDeclaration(parsed.sourceFile, node),
				filePath: parsed.relativePath,
				line: lineFor(parsed.sourceFile, node),
			});
		}

		ts.forEachChild(node, visit);
	};

	visit(parsed.sourceFile);
	return declarations;
};

const duplicateTypeKeyOf = (declaration: ExportedTypeDeclaration): string =>
	`${declaration.name}\0${declaration.signature}`;

const detectDuplicateExportedTypes = (parsedSources: ParsedSource[]): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const seen = new Map<string, ExportedTypeDeclaration>();

	for (const parsed of parsedSources) {
		if (!TS_EXTENSIONS.has(parsed.ext)) continue;
		for (const declaration of exportedTypesOf(parsed)) {
			const key = duplicateTypeKeyOf(declaration);
			const previous = seen.get(key);
			if (!previous) {
				seen.set(key, declaration);
				continue;
			}

			if (previous.filePath === declaration.filePath) continue;
			diagnostics.push(
				makeDiagnostic(
					declaration.filePath,
					declaration.line,
					"ai-slop/duplicate-type-declaration",
					`Exported type '${declaration.name}' duplicates an existing declaration`,
					`Reuse or import the existing type from ${previous.filePath} instead of re-declaring the same shape in another file.`,
				),
			);
		}
	}

	return diagnostics;
};

export const detectDefensivePatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const parsedSources: ParsedSource[] = [];

	for (const filePath of getSourceFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		const ext = path.extname(filePath);
		if (!JS_TS_EXTENSIONS.has(ext)) continue;

		const sourceFile = ts.createSourceFile(
			filePath,
			content,
			ts.ScriptTarget.Latest,
			true,
			scriptKindFor(ext),
		);

		parsedSources.push({ sourceFile, relativePath, ext });
		diagnostics.push(...detectRedundantTryCatch(sourceFile, relativePath));
		if (TS_EXTENSIONS.has(ext)) {
			diagnostics.push(...detectPrimitiveCoercions(sourceFile, relativePath));
		}
	}

	diagnostics.push(...detectDuplicateExportedTypes(parsedSources));
	return diagnostics;
};
