import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments } from "../../utils/source-masker.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

// Top-level ES module imports only — side-effect / require / dynamic-import legitimately repeat and are excluded.
const IMPORT_FROM_RE = /^\s*import\s+([^;]*?)\s+from\s+["']([^"']+)["']/;

// A leading `import type {...}` is a type-only statement.
const TYPE_ONLY_RE = /^\s*type\b/;

// `import { type Foo, type Bar }` with no value bindings is also type-only under consistent-type-imports.
const VALUE_BINDING_RE = /\{([^}]*)\}/;

// `import * as ns` cannot be merged with a named/default import from the same module.
const NAMESPACE_RE = /\*\s+as\s+/;

interface ImportLine {
	spec: string;
	line: number;
	typeOnly: boolean;
	namespace: boolean;
}

const isTypeOnly = (clause: string): boolean => {
	if (TYPE_ONLY_RE.test(clause)) return true;
	const braces = VALUE_BINDING_RE.exec(clause);
	if (!braces) return false;
	const members = braces[1]
		.split(",")
		.map((member) => member.trim())
		.filter((member) => member.length > 0);
	return members.length > 0 && members.every((member) => /^type\b/.test(member));
};

const extractImportLines = (content: string): ImportLine[] => {
	const lines = content.split("\n");
	const results: ImportLine[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const match = IMPORT_FROM_RE.exec(line);
		if (!match) continue;
		results.push({
			spec: match[2],
			line: i + 1,
			typeOnly: isTypeOnly(match[1]),
			namespace: NAMESPACE_RE.test(match[1]),
		});
	}
	return results;
};

export const detectDuplicateImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!JS_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const imports = extractImportLines(maskComments(content, path.extname(filePath)));
		if (imports.length < 2) continue;

		// Bucket by binding kind: a value+type pair is the consistent-type-imports shape, and
		// `import * as x` cannot merge with a named import, so neither is a real duplicate.
		const byBucket = new Map<string, ImportLine[]>();
		for (const imp of imports) {
			const kind = imp.namespace ? "ns" : imp.typeOnly ? "type" : "value";
			const key = `${kind}\0${imp.spec}`;
			const list = byBucket.get(key) ?? [];
			list.push(imp);
			byBucket.set(key, list);
		}

		const relPath = relativePosix(context.rootDirectory, filePath);
		for (const occurrences of byBucket.values()) {
			const { spec } = occurrences[0];
			if (occurrences.length < 2) continue;
			// Flag the second-and-later occurrences; the first one is the canonical home.
			for (const dup of occurrences.slice(1)) {
				const firstLine = occurrences[0].line;
				diagnostics.push({
					filePath: relPath,
					engine: "ai-slop",
					rule: "ai-slop/duplicate-import",
					severity: "warning",
					message: `"${spec}" is also imported on line ${firstLine}. Merge into a single import statement.`,
					help: "Two imports from the same module split readers' attention and grow the import block. Run aislop fix to merge them automatically.",
					line: dup.line,
					column: 1,
					category: "AI Slop",
					fixable: true,
				});
			}
		}
	}

	return diagnostics;
};
