import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

interface NamedImport {
	name: string;
	alias?: string;
	isType: boolean;
}

interface ImportStmt {
	lineIndex: number;
	module: string;
	default?: string;
	namespace?: string;
	named: NamedImport[];
	isTypeOnly: boolean;
	isSideEffect: boolean;
}

const IMPORT_FROM_RE = /^\s*import\s+(.*?)\s+from\s+["']([^"']+)["']\s*;?\s*$/;
const SIDE_EFFECT_RE = /^\s*import\s+["']([^"']+)["']\s*;?\s*$/;

const parseNamedClause = (clause: string): NamedImport[] => {
	const inner = clause.trim().slice(1, -1).trim();
	if (inner.length === 0) return [];
	const items: NamedImport[] = [];
	for (const part of inner.split(",")) {
		const trimmed = part.trim();
		if (!trimmed) continue;
		let isType = false;
		let working = trimmed;
		if (/^type\s+/.test(working)) {
			isType = true;
			working = working.replace(/^type\s+/, "");
		}
		const aliasMatch = working.match(/^(\w+)\s+as\s+(\w+)$/);
		if (aliasMatch) {
			items.push({ name: aliasMatch[1], alias: aliasMatch[2], isType });
			continue;
		}
		if (/^\w+$/.test(working)) items.push({ name: working, isType });
	}
	return items;
};

const parseImportClause = (
	clause: string,
): Omit<ImportStmt, "lineIndex" | "module" | "isSideEffect"> => {
	let rest = clause.trim();
	let isTypeOnly = false;
	if (/^type\s+/.test(rest)) {
		isTypeOnly = true;
		rest = rest.replace(/^type\s+/, "");
	}
	const out: Omit<ImportStmt, "lineIndex" | "module" | "isSideEffect"> = {
		named: [],
		isTypeOnly,
	};
	// Try default-and-rest first
	const defMatch = rest.match(/^([A-Za-z_$][\w$]*)\s*(?:,\s*(.+))?$/);
	if (defMatch && !rest.startsWith("{") && !rest.startsWith("*")) {
		out.default = defMatch[1];
		rest = defMatch[2]?.trim() ?? "";
	}
	if (rest.startsWith("*")) {
		const nsMatch = rest.match(/^\*\s+as\s+(\w+)/);
		if (nsMatch) out.namespace = nsMatch[1];
		return out;
	}
	if (rest.startsWith("{")) out.named = parseNamedClause(rest);
	return out;
};

const parseImportLine = (line: string, lineIndex: number): ImportStmt | null => {
	const sideEffect = line.match(SIDE_EFFECT_RE);
	if (sideEffect) {
		return {
			lineIndex,
			module: sideEffect[1],
			named: [],
			isTypeOnly: false,
			isSideEffect: true,
		};
	}
	const m = line.match(IMPORT_FROM_RE);
	if (!m) return null;
	return {
		lineIndex,
		module: m[2],
		isSideEffect: false,
		...parseImportClause(m[1]),
	};
};

const formatNamed = (n: NamedImport, stripType: boolean): string => {
	const prefix = n.isType && !stripType ? "type " : "";
	const suffix = n.alias ? ` as ${n.alias}` : "";
	return `${prefix}${n.name}${suffix}`;
};

// Returns the merged single-line import text, or null when the group can't be safely merged.
const mergeImports = (group: ImportStmt[]): string | null => {
	if (group.some((s) => s.isSideEffect)) return null;
	if (group.some((s) => s.namespace !== undefined)) return null;
	if (group.some((s) => s.isTypeOnly && s.default !== undefined)) return null;

	const defaults = group.map((s) => s.default).filter((d): d is string => d !== undefined);
	const uniqueDefaults = Array.from(new Set(defaults));
	if (uniqueDefaults.length > 1) return null;
	const defaultName = uniqueDefaults[0];

	const merged = new Map<string, NamedImport>();
	for (const stmt of group) {
		for (const nm of stmt.named) {
			const key = nm.alias ?? nm.name;
			const isType = nm.isType || stmt.isTypeOnly;
			const existing = merged.get(key);
			if (!existing) {
				merged.set(key, { ...nm, isType });
			} else {
				existing.isType = existing.isType && isType;
			}
		}
	}

	const insertionOrder = Array.from(merged.values());
	// Idiomatic style: `{ value, type Type }` — value items first, type items after.
	const namedList = [
		...insertionOrder.filter((n) => !n.isType),
		...insertionOrder.filter((n) => n.isType),
	];
	const allTypeOnly = namedList.length > 0 && namedList.every((n) => n.isType);
	const module = group[0].module;

	if (!defaultName && namedList.length === 0) return null;

	if (!defaultName && allTypeOnly) {
		const items = namedList.map((n) => formatNamed(n, true)).join(", ");
		return `import type { ${items} } from "${module}";`;
	}

	const parts: string[] = [];
	if (defaultName) parts.push(defaultName);
	if (namedList.length > 0) {
		const items = namedList.map((n) => formatNamed(n, false)).join(", ");
		parts.push(`{ ${items} }`);
	}
	return `import ${parts.join(", ")} from "${module}";`;
};

export const fixDuplicateImports = async (context: EngineContext): Promise<void> => {
	const files = getSourceFiles(context);
	for (const filePath of files) {
		if (!JS_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const imports: ImportStmt[] = [];
		for (let i = 0; i < lines.length; i++) {
			const stmt = parseImportLine(lines[i], i);
			if (stmt) imports.push(stmt);
		}
		if (imports.length < 2) continue;

		const groups = new Map<string, ImportStmt[]>();
		for (const stmt of imports) {
			const list = groups.get(stmt.module) ?? [];
			list.push(stmt);
			groups.set(stmt.module, list);
		}

		const linesToRemove = new Set<number>();
		const replacements = new Map<number, string>();
		let modified = false;
		for (const group of groups.values()) {
			if (group.length < 2) continue;
			const merged = mergeImports(group);
			if (!merged) continue;
			replacements.set(group[0].lineIndex, merged);
			for (const stmt of group.slice(1)) linesToRemove.add(stmt.lineIndex);
			modified = true;
		}
		if (!modified) continue;

		const next = [...lines];
		for (const [idx, replacement] of replacements) next[idx] = replacement;
		const sortedRemove = Array.from(linesToRemove).sort((a, b) => b - a);
		for (const idx of sortedRemove) next.splice(idx, 1);

		fs.writeFileSync(filePath, next.join("\n"));
	}
};
