import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const GO_EXTENSIONS = new Set([".go"]);

const PACKAGE_DECL_RE = /^\s*package\s+(\w+)/;
const PANIC_CALL_RE = /\bpanic\s*\(/;
const COMMENT_LINE_RE = /^\s*\/\//;
const NIL_GUARD_RE = /^\s*if\s+[\w.]+(?:\(\))?\s*==\s*nil\s*\{?\s*$/;
const SHORT_STRING_PANIC_RE = /\bpanic\s*\(\s*"[^"]{1,40}"\s*\)/;
const GO_TEST_SUPPORT_PATH_RE =
	/(?:^|\/)(?:testdata|testutil|testutils|tstest|ethtest|v4test|testing)(?:\/|$)/i;

const detectPackageName = (lines: string[]): string | null => {
	for (const line of lines) {
		const m = PACKAGE_DECL_RE.exec(line);
		if (m) return m[1];
	}
	return null;
};

// A comment within N lines above the panic signals deliberate intent.
const PANIC_INTENT_LOOKBACK = 3;

const hasIntentComment = (lines: string[], panicLineIdx: number): boolean => {
	for (let j = panicLineIdx - 1; j >= Math.max(0, panicLineIdx - PANIC_INTENT_LOOKBACK); j--) {
		if (COMMENT_LINE_RE.test(lines[j])) return true;
	}
	return false;
};

// `if x == nil { panic("nil X") }` is a precondition guard, not unwound flow.
const isNilGuardPanic = (lines: string[], panicLineIdx: number, line: string): boolean => {
	if (!SHORT_STRING_PANIC_RE.test(line)) return false;
	for (let j = panicLineIdx - 1; j >= Math.max(0, panicLineIdx - 2); j--) {
		const prev = lines[j];
		if (prev.trim() === "") continue;
		return NIL_GUARD_RE.test(prev);
	}
	return false;
};

const flagLibraryPanic = (
	lines: string[],
	relPath: string,
	pkg: string,
	out: Diagnostic[],
): void => {
	if (pkg === "main") return;
	if (GO_TEST_SUPPORT_PATH_RE.test(relPath) || /test$/i.test(pkg)) return;
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (COMMENT_LINE_RE.test(line)) continue;
		// Skip lines that only mention `panic` inside a string or a struct field name.
		PANIC_CALL_RE.lastIndex = 0;
		if (!PANIC_CALL_RE.test(line)) continue;
		if (hasIntentComment(lines, i)) continue;
		if (isNilGuardPanic(lines, i, line)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/go-library-panic",
			severity: "warning",
			message: `\`panic()\` in package \`${pkg}\` (non-main, non-test). Library code should return errors, not unwind the goroutine.`,
			help: "Convert to `return fmt.Errorf(...)` (or a wrapped error) and let the caller decide. Reserve `panic` for genuinely-impossible states (corrupt internal invariants), and mark those with a comment so future readers know it's intentional.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

export const detectGoPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!GO_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;
		// `_test.go` files are allowed to panic — that's how t.Fatal-equivalents read.
		if (filePath.endsWith("_test.go")) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const pkg = detectPackageName(lines);
		if (!pkg) continue;

		const relPath = relativePosix(context.rootDirectory, filePath);
		flagLibraryPanic(lines, relPath, pkg, diagnostics);
	}

	return diagnostics;
};
