import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JS_TS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const HIDDEN_FALLBACK_CONTEXT_RE =
	/\b(?:fallback|direct\s+api|just in case|should never happen|impossible|missing|not provided|doesn'?t provide|caller\s+doesn'?t\s+provide|failed|failure|invalid|no diagnostics|no results|no files|empty diagnostics|empty results|empty files)\b/i;
const FAILURE_STATE_NAME_RE =
	/\b(?:count|total|diagnostic|diagnostics|file|files|sourcefile|result|results|error|errors|failure|failed|invalid|missing|state|status|success|response|output|input)\b/i;
const FAILURE_STATE_COMPACT_RE =
	/(?:count|diagnostic|file|sourcefile|result|error|failure|failed|invalid|missing|state|status|success|response|output|input)/;
const DEFAULT_VALUE_NAME_RE =
	/^(?:default(?:value|result|count)?|fallback(?:value|result|count)?|empty(?:result|response|list|array)?|success(?:result|response)?|ok(?:result|response)?)$/i;
const LOG_OR_THROW_RE =
	/\b(?:throw|console\.(?:debug|info|warn|warning|error|log)|(?:logger|log)\.(?:debug|info|warn|warning|error|exception|log))\b/;
const STATUS_TOKEN_RE =
	/^(?:ok|okay|success|succeeded|passed?|valid|healthy|done|ready|active|enabled|true|yes|good|online|live)$/i;

const scriptKindFor = (ext: string): ts.ScriptKind => {
	switch (ext) {
		case ".tsx":
			return ts.ScriptKind.TSX;
		case ".jsx":
			return ts.ScriptKind.JSX;
		case ".js":
		case ".mjs":
		case ".cjs":
			return ts.ScriptKind.JS;
		default:
			return ts.ScriptKind.TS;
	}
};

const lineFor = (sourceFile: ts.SourceFile, node: ts.Node): number =>
	sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1;

const makeHiddenFallbackDiagnostic = (
	filePath: string,
	line: number,
	message: string,
	help: string,
): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule: "ai-slop/hidden-fallback",
	severity: "warning",
	message,
	help,
	line,
	column: 0,
	category: "AI Slop",
	fixable: false,
});

const nameTextOf = (name: ts.PropertyName): string | null => {
	if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
		return name.text;
	}
	return null;
};

const isTrueLike = (expression: ts.Expression): boolean =>
	expression.kind === ts.SyntaxKind.TrueKeyword ||
	(ts.isStringLiteral(expression) && /^(?:true|ok|success)$/i.test(expression.text));

const isSuccessLikeObject = (expression: ts.ObjectLiteralExpression): boolean =>
	expression.properties.some((property) => {
		if (!ts.isPropertyAssignment(property)) return false;
		const name = nameTextOf(property.name);
		return (
			name !== null && /^(?:ok|success|status)$/i.test(name) && isTrueLike(property.initializer)
		);
	});

const isSafeLookingDefault = (expression: ts.Expression): boolean => {
	if (
		ts.isNumericLiteral(expression) ||
		ts.isStringLiteral(expression) ||
		expression.kind === ts.SyntaxKind.TrueKeyword ||
		expression.kind === ts.SyntaxKind.FalseKeyword ||
		expression.kind === ts.SyntaxKind.NullKeyword
	) {
		return true;
	}
	if (ts.isIdentifier(expression)) {
		return expression.text === "undefined" || DEFAULT_VALUE_NAME_RE.test(expression.text);
	}
	if (ts.isArrayLiteralExpression(expression)) {
		return expression.elements.length === 0;
	}
	if (ts.isObjectLiteralExpression(expression)) {
		return expression.properties.length === 0 || isSuccessLikeObject(expression);
	}
	return false;
};

const expressionText = (sourceFile: ts.SourceFile, expression: ts.Expression): string =>
	expression.getText(sourceFile);

const expressionNamesFailureState = (
	sourceFile: ts.SourceFile,
	expression: ts.Expression,
): boolean => {
	const text = expressionText(sourceFile, expression);
	const compact = text.toLowerCase().replace(/[^a-z0-9]/g, "");
	return FAILURE_STATE_NAME_RE.test(text) || FAILURE_STATE_COMPACT_RE.test(compact);
};

const defaultLooksLikeFallback = (expression: ts.Expression): boolean =>
	ts.isIdentifier(expression) && DEFAULT_VALUE_NAME_RE.test(expression.text);

const isMathMinMaxFallback = (
	sourceFile: ts.SourceFile,
	expression: ts.CallExpression,
): boolean => {
	if (!ts.isPropertyAccessExpression(expression.expression)) return false;
	const target = expression.expression;
	if (!ts.isIdentifier(target.expression) || target.expression.text !== "Math") return false;
	if (target.name.text !== "max" && target.name.text !== "min") return false;
	if (expression.arguments.length < 2) return false;

	const hasNumericDefault = expression.arguments.some((arg) => ts.isNumericLiteral(arg));
	const hasFailureStateArgument = expression.arguments.some((arg) =>
		expressionNamesFailureState(sourceFile, arg),
	);
	return hasNumericDefault && hasFailureStateArgument;
};

const isEnvAccess = (expression: ts.Expression): boolean => {
	if (!ts.isPropertyAccessExpression(expression) && !ts.isElementAccessExpression(expression)) {
		return false;
	}
	const target = expression.expression;
	return (
		ts.isPropertyAccessExpression(target) &&
		ts.isIdentifier(target.expression) &&
		target.expression.text === "process" &&
		target.name.text === "env"
	);
};

const isHiddenFallbackExpression = (
	sourceFile: ts.SourceFile,
	expression: ts.Expression,
): boolean => {
	if (ts.isBinaryExpression(expression)) {
		const isFallbackOperator =
			expression.operatorToken.kind === ts.SyntaxKind.BarBarToken ||
			expression.operatorToken.kind === ts.SyntaxKind.QuestionQuestionToken;
		if (!isFallbackOperator || !isSafeLookingDefault(expression.right)) return false;
		if (isEnvAccess(expression.left)) return false;
		if (ts.isStringLiteral(expression.right) && !STATUS_TOKEN_RE.test(expression.right.text)) {
			return false;
		}
		return (
			defaultLooksLikeFallback(expression.right) ||
			expressionNamesFailureState(sourceFile, expression.left) ||
			expressionNamesFailureState(sourceFile, expression)
		);
	}

	return ts.isCallExpression(expression) && isMathMinMaxFallback(sourceFile, expression);
};

const nearbyText = (sourceFile: ts.SourceFile, node: ts.Node): string => {
	const line = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line;
	const lines = sourceFile.text.split(/\r?\n/);
	return lines.slice(Math.max(0, line - 4), Math.min(lines.length, line + 1)).join("\n");
};

const hasHiddenFallbackContext = (sourceFile: ts.SourceFile, node: ts.Node): boolean =>
	HIDDEN_FALLBACK_CONTEXT_RE.test(nearbyText(sourceFile, node));

const catchSurfacesFailure = (
	sourceFile: ts.SourceFile,
	catchClause: ts.CatchClause,
	returnExpression: ts.Expression,
): boolean => {
	const bodyText = catchClause.block.getText(sourceFile);
	if (LOG_OR_THROW_RE.test(bodyText)) return true;

	const binding = catchClause.variableDeclaration?.name;
	if (!binding || !ts.isIdentifier(binding)) return false;
	return new RegExp(`\\b${binding.text}\\b`).test(returnExpression.getText(sourceFile));
};

const isSuccessLikeReturn = (expression: ts.Expression): boolean =>
	ts.isObjectLiteralExpression(expression) && isSuccessLikeObject(expression);

const shouldFlagCatchFallback = (
	sourceFile: ts.SourceFile,
	catchClause: ts.CatchClause,
	expression: ts.Expression,
): boolean =>
	hasHiddenFallbackContext(sourceFile, catchClause) ||
	defaultLooksLikeFallback(expression) ||
	isSuccessLikeReturn(expression) ||
	isHiddenFallbackExpression(sourceFile, expression);

const detectHiddenCatchFallback = (
	sourceFile: ts.SourceFile,
	catchClause: ts.CatchClause,
	relativePath: string,
	diagnostics: Diagnostic[],
): void => {
	for (const statement of catchClause.block.statements) {
		if (!ts.isReturnStatement(statement) || !statement.expression) continue;
		const expression = statement.expression;
		if (!isSafeLookingDefault(expression) && !isHiddenFallbackExpression(sourceFile, expression)) {
			continue;
		}
		if (!shouldFlagCatchFallback(sourceFile, catchClause, expression)) continue;
		if (catchSurfacesFailure(sourceFile, catchClause, expression)) continue;

		diagnostics.push(
			makeHiddenFallbackDiagnostic(
				relativePath,
				lineFor(sourceFile, statement),
				"Catch returns a safe-looking fallback without surfacing the failure",
				"Log or return the failure explicitly, rethrow with context, or make the fallback an intentional typed outcome.",
			),
		);
	}
};

const detectHiddenFallbacksInSource = (
	sourceFile: ts.SourceFile,
	relativePath: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];

	const reportIfHiddenFallback = (node: ts.Node, expression: ts.Expression): void => {
		if (!hasHiddenFallbackContext(sourceFile, node)) return;
		if (!isHiddenFallbackExpression(sourceFile, expression)) return;

		diagnostics.push(
			makeHiddenFallbackDiagnostic(
				relativePath,
				lineFor(sourceFile, node),
				"Fallback turns missing, failed, or impossible state into a safe-looking value",
				"Handle the missing input explicitly: require the value, return a typed error, or name the conservative estimate so callers know it is not authoritative.",
			),
		);
	};

	const visit = (node: ts.Node): void => {
		if (ts.isReturnStatement(node) && node.expression) {
			reportIfHiddenFallback(node, node.expression);
		}

		if (ts.isVariableDeclaration(node) && node.initializer) {
			reportIfHiddenFallback(node, node.initializer);
		}

		if (ts.isCatchClause(node)) {
			detectHiddenCatchFallback(sourceFile, node, relativePath, diagnostics);
		}

		ts.forEachChild(node, visit);
	};

	visit(sourceFile);
	return diagnostics;
};

export const detectHiddenFallbacks = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];

	for (const filePath of getSourceFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		const ext = path.extname(filePath);
		if (!JS_TS_EXTENSIONS.has(ext)) continue;

		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const sourceFile = ts.createSourceFile(
			filePath,
			content,
			ts.ScriptTarget.Latest,
			true,
			scriptKindFor(ext),
		);
		diagnostics.push(...detectHiddenFallbacksInSource(sourceFile, relativePath));
	}

	return diagnostics;
};
