import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { type CommentBlock, collectBlocks, getCommentSyntax } from "./comment-blocks.js";
import { SUPPORTED_EXTS } from "./narrative-comments-patterns.js";
import { isNonProductionPath } from "./non-production-paths.js";

// References to the AI's own plan/process or to a task/spec/ticket it was working from.
const PLAN_REFERENCE_RES: RegExp[] = [
	// A numbered marker followed by a delimiter is plan narration; a bare numbered step
	// mid-sentence is domain usage (a UI wizard), not AI narration.
	/^(?:stage|step|phase)\s+\d+\s*[:.\-–—]/i,
	/\bstep\s+\d+\s+of\s+the\s+plan\b/i,
	/\bas\s+(?:per|requested)\s+(?:the\s+)?(?:requirements?|spec|task|ticket|prompt|instructions?)\b/i,
	/\bper\s+the\s+(?:spec|requirements?|task|ticket|plan|prompt|instructions?)\b/i,
	/\bfrom\s+the\s+(?:task|todo|plan|spec|ticket|prompt|requirements?)\b/i,
	/\bimplement(?:ing|s|ed)?\s+use\s*case\s+\d*/i,
	/\b(?:requirements?\s+doc|requirement\s+\d+)\b/i,
	/\bas\s+(?:instructed|specified|outlined)\s+(?:above|below|in\s+the)\b/i,
];

// Narration of how the code changed: before/after state that belongs in a PR diff, not source.
const BEFORE_AFTER_RES: RegExp[] = [
	/\bpreviously[,:]?\s+(?:this|we|it|the)\b/i,
	/\bused\s+to\s+(?:be|use|call|return|do|have|rely)\b/i,
	/\bchanged\s+(?:\w+\s+){0,3}from\s+.+\bto\b/i,
	/\bno\s+longer\s+(?:needed|used|required|necessary|calls?|returns?|does)\b/i,
	/\bthis\s+was\s+.+\bbut\s+now\b/i,
	/\bwe\s+(?:now|used\s+to)\s+(?:no\s+longer\s+)?(?:use|call|return|do|have)\b/i,
	/\breplaced\s+the\s+(?:old|previous|former)\b/i,
	/\b(?:was|were)\s+(?:renamed|moved|removed|refactored|extracted)\s+(?:from|to|out\s+of)\b/i,
];

// Generic exemptions: real WHY context, TODO/FIXME, dotted identifiers, and tagged docs stay.
const WHY_OR_TODO_RE =
	/\b(?:because|since|otherwise|todo|fixme|hack|note:|reason:|workaround|see\s+(?:issue|#))\b/i;

const looksLikeLicenseHeader = (block: CommentBlock): boolean => {
	if (block.startLine !== 1) return false;
	const text = block.rawLines.join(" ").toLowerCase();
	return (
		text.includes("copyright") ||
		text.includes("license") ||
		text.includes("spdx-license-identifier")
	);
};

const looksLikeSuppressDirective = (block: CommentBlock): boolean =>
	block.rawLines.some((line) =>
		/\b(?:biome-ignore|eslint-disable|ts-ignore|ts-expect-error|@ts-\w+|noqa|pylint:\s*disable|rubocop:disable|noinspection|phpcs:disable)\b/.test(
			line,
		),
	);

const matchMetaSignal = (block: CommentBlock): string | null => {
	if (looksLikeLicenseHeader(block)) return null;
	if (looksLikeSuppressDirective(block)) return null;
	if (block.kind === "jsdoc" && block.hasMeaningfulJsdocTag) return null;
	if (block.isRustDoc) return null;

	const joined = block.prose.join(" ");
	if (joined.trim().length === 0) return null;
	if (WHY_OR_TODO_RE.test(joined)) return null;

	if (PLAN_REFERENCE_RES.some((re) => re.test(joined))) return "plan/process reference";
	if (BEFORE_AFTER_RES.some((re) => re.test(joined))) return "before/after state narration";
	return null;
};

export const detectMetaComments = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const ext = path.extname(filePath);
		if (!SUPPORTED_EXTS.has(ext)) continue;
		if (isAutoGenerated(filePath)) continue;
		const syntax = getCommentSyntax(ext);
		if (!syntax) continue;

		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const blocks = collectBlocks(content.split("\n"), syntax);
		for (const block of blocks) {
			const reason = matchMetaSignal(block);
			if (!reason) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/meta-comment",
				severity: "warning",
				message: `Meta/plan comment (${reason})`,
				help: "Remove — references to the build plan or before/after code state belong in PR descriptions and commit messages, not source.",
				line: block.startLine,
				column: 0,
				category: "Comments",
				fixable: false,
			});
		}
	}

	return diagnostics;
};
