import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { type CommentBlock, collectBlocks, getCommentSyntax } from "./comment-blocks.js";
import {
	CROSS_REFERENCE_PHRASES,
	CSHARP_DECL_START,
	CSHARP_DECL_START_FALLBACK,
	DECL_START,
	DECORATIVE_SECTION_HEADER,
	DECORATIVE_SEPARATOR,
	EXPLANATORY_OPENERS,
	EXPLANATORY_WHY_MARKERS,
	EXPORT_DEFAULT,
	GO_DECL_START,
	JAVA_DECL_START,
	JAVA_DECL_START_FALLBACK,
	JUSTIFICATION_OPENERS,
	PHP_DECL_START,
	PY_DECL_START,
	RUBY_DECL_START,
	RUST_DECL_START,
	SECTION_HEADER,
	SUPPORTED_EXTS,
	TS_MEMBER_DECL_START,
} from "./narrative-comments-patterns.js";
import { isNonProductionPath } from "./non-production-paths.js";

const looksLikeDeclarationPreamble = (nextLine: string | null, ext: string): boolean => {
	if (nextLine === null) return false;
	if (DECL_START.test(nextLine) || EXPORT_DEFAULT.test(nextLine)) return true;

	switch (ext) {
		case ".py":
			return PY_DECL_START.test(nextLine);
		case ".go":
			return GO_DECL_START.test(nextLine);
		case ".rs":
			return RUST_DECL_START.test(nextLine);
		case ".rb":
			return RUBY_DECL_START.test(nextLine);
		case ".java":
			return JAVA_DECL_START.test(nextLine) || JAVA_DECL_START_FALLBACK.test(nextLine);
		case ".php":
			return PHP_DECL_START.test(nextLine);
		case ".cs":
			return CSHARP_DECL_START.test(nextLine) || CSHARP_DECL_START_FALLBACK.test(nextLine);
		case ".ts":
		case ".tsx":
		case ".js":
		case ".jsx":
		case ".mjs":
		case ".cjs":
			return TS_MEMBER_DECL_START.test(nextLine);
		default:
			return false;
	}
};

const looksLikeLicenseHeader = (block: CommentBlock): boolean => {
	if (block.startLine !== 1) return false;
	const text = block.rawLines.join(" ").toLowerCase();
	return (
		text.includes("copyright") ||
		text.includes("license") ||
		text.includes("spdx-license-identifier")
	);
};

const looksLikeSuppressDirective = (block: CommentBlock): boolean =>
	block.rawLines.some((l) =>
		/\b(biome-ignore|eslint-disable|ts-ignore|ts-expect-error|@ts-\w+|noqa|pylint:\s*disable|rubocop:disable|noinspection|phpcs:disable)\b/.test(
			l,
		),
	);

const GO_DECL_NAME_RE = /^(?:func|type|var|const)\s+(?:\([^)]*\)\s*)?(\w+)/;
const GO_FIELD_LEAD_RE = /^(\w+)\s+/;
const GO_KEYWORDS = new Set([
	"return",
	"if",
	"for",
	"switch",
	"case",
	"default",
	"go",
	"select",
	"defer",
	"else",
	"break",
	"continue",
	"goto",
	"package",
	"import",
	"map",
	"chan",
	"range",
]);
const looksLikeGoDocComment = (block: CommentBlock, ext: string): boolean => {
	if (ext !== ".go" || block.kind !== "line") return false;
	const next = block.nextNonBlankLine;
	if (!next) return false;
	const trimmedNext = next.trim();
	const firstProse = block.prose.find((l) => l.length > 0) ?? "";
	const firstWord = firstProse.split(/\s+/)[0] ?? "";

	const declMatch = GO_DECL_NAME_RE.exec(trimmedNext);
	if (declMatch && firstWord === declMatch[1]) return true;

	// Struct / interface field docs: comment's first word matches the field name on the next line.
	const fieldMatch = GO_FIELD_LEAD_RE.exec(trimmedNext);
	if (fieldMatch && !GO_KEYWORDS.has(fieldMatch[1]) && firstWord === fieldMatch[1]) return true;

	return false;
};

// Ruby YARD tags, RDoc directives, or `##` markers signal documentation, not narrative slop.
const RUBY_DOC_INDICATORS = /^\s*#\s*(?:#|@\w+|:[\w-]+:|=begin|=end)/;
const looksLikeRubyDocBlock = (block: CommentBlock, ext: string): boolean => {
	if (ext !== ".rb" || block.kind !== "line") return false;
	return block.rawLines.some((line) => RUBY_DOC_INDICATORS.test(line));
};

const DOC_INDICATOR_RE =
	/`[^`]+`|\|\s*[-:]+\s*\||```|\b(?:note|warning|warn|caveat|example|caution|see|todo|fixme|hack|reason|deprecated|deprecation|migration|legacy|historical|context):|\(e\.g\.[^)]+\)|\(i\.e\.[^)]+\)|\b\w+\.\w+(?:\.\w+)+\b|\[[\w/.-]+\]/i;
const hasDocIndicator = (block: CommentBlock): boolean => {
	const joined = block.prose.join(" ");
	if (DOC_INDICATOR_RE.test(joined)) return true;
	for (const l of block.prose) {
		if (/^[-]\s/.test(l)) return true;
	}
	return false;
};

const hasPreambleSlopSignal = (block: CommentBlock): boolean => {
	const joined = block.prose.join(" ");
	for (const l of block.prose) {
		if (EXPLANATORY_OPENERS.test(l)) return true;
		if (JUSTIFICATION_OPENERS.some((re) => re.test(l))) return true;
	}
	return CROSS_REFERENCE_PHRASES.some((re) => re.test(joined));
};

const detectNarrativeInBlock = (
	block: CommentBlock,
	ext: string,
): { matched: boolean; reason: string } => {
	if (looksLikeLicenseHeader(block)) return { matched: false, reason: "" };
	if (looksLikeSuppressDirective(block)) return { matched: false, reason: "" };
	if (block.kind === "jsdoc" && block.hasMeaningfulJsdocTag) return { matched: false, reason: "" };
	if (block.isRustDoc) return { matched: false, reason: "" };
	if (looksLikeGoDocComment(block, ext)) return { matched: false, reason: "" };
	if (looksLikeRubyDocBlock(block, ext)) return { matched: false, reason: "" };

	if (
		block.kind === "line" &&
		block.prose.some((l) => DECORATIVE_SEPARATOR.test(l) || DECORATIVE_SECTION_HEADER.test(l))
	) {
		return { matched: true, reason: "decorative separator" };
	}

	if (block.kind === "line" && block.prose.some((l) => SECTION_HEADER.test(l))) {
		return { matched: true, reason: "phase/section header" };
	}

	const joined = block.prose.join(" ");
	const hasWhyMarker = EXPLANATORY_WHY_MARKERS.test(joined);

	if (hasWhyMarker || hasDocIndicator(block)) {
		return { matched: false, reason: "" };
	}

	if (
		block.kind === "line" &&
		block.prose.length >= 3 &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext) &&
		hasPreambleSlopSignal(block)
	) {
		return { matched: true, reason: "multi-line preamble before declaration" };
	}

	if (
		block.kind === "jsdoc" &&
		block.prose.length >= 3 &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext) &&
		hasPreambleSlopSignal(block)
	) {
		return { matched: true, reason: "JSDoc preamble with slop signal" };
	}

	if (CROSS_REFERENCE_PHRASES.some((re) => re.test(joined))) {
		return { matched: true, reason: "cross-reference commentary" };
	}

	if (block.kind === "line") {
		for (const l of block.prose) {
			if (JUSTIFICATION_OPENERS.some((re) => re.test(l))) {
				return { matched: true, reason: "justification prose" };
			}
		}
	}

	if (
		block.kind === "line" &&
		block.rawLines.length === 1 &&
		EXPLANATORY_OPENERS.test(block.prose[0] ?? "") &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext)
	) {
		return { matched: true, reason: "explanatory preamble" };
	}

	const nonEmptyProseCount = block.prose.filter((l) => l.length > 0).length;
	const isAboveDeclaration = looksLikeDeclarationPreamble(block.nextNonBlankLine, ext);

	if (nonEmptyProseCount >= 5 && !isAboveDeclaration && hasPreambleSlopSignal(block)) {
		return { matched: true, reason: "long narrative block" };
	}

	if (
		nonEmptyProseCount >= 3 &&
		!hasWhyMarker &&
		block.kind === "line" &&
		!isAboveDeclaration &&
		hasPreambleSlopSignal(block)
	) {
		return { matched: true, reason: "multi-line narrative prose" };
	}

	return { matched: false, reason: "" };
};

export const detectNarrativeComments = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const ext = path.extname(filePath);
		if (!SUPPORTED_EXTS.has(ext)) continue;
		if (isAutoGenerated(filePath)) continue;
		const syntax = getCommentSyntax(ext);
		if (!syntax) continue;

		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const blocks = collectBlocks(lines, syntax);

		for (const block of blocks) {
			const { matched, reason } = detectNarrativeInBlock(block, ext);
			if (!matched) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/narrative-comment",
				severity: "warning",
				message: `Narrative comment block (${reason})`,
				help: "Remove — narrative/decorative comments belong in PR descriptions, not source. Code should be self-explanatory.",
				line: block.startLine,
				column: 0,
				category: "Comments",
				fixable: true,
			});
		}
	}

	return diagnostics;
};
