import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { scanPythonDocstrings } from "../../utils/python-docstrings.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const PY_EXTENSIONS = new Set([".py"]);

const BARE_EXCEPT_RE = /^\s*except\s*:\s*(?:#.*)?$/;
const BROAD_EXCEPT_RE = /^\s*except\s+(Exception|BaseException)\s*(?:as\s+\w+)?\s*:\s*(?:#.*)?$/;
const PRINT_RE = /^\s*print\s*\(/;
const DEF_RE = /^\s*(?:async\s+)?def\s+\w+\s*\(/;
const MUTABLE_DEFAULT_RE = /(\w+)\s*(?::\s*[^,)=]+)?\s*=\s*(\[\s*\]|\{\s*\}|set\(\s*\))/g;
// True when the quote at `quoteIndex` opens an f-string: immediately preceded
// by a short run of string-prefix letters containing `f`/`F` that is not the
// tail of a longer identifier.
const isFStringOpener = (text: string, quoteIndex: number): boolean => {
	let start = quoteIndex;
	while (start > 0 && /[A-Za-z]/.test(text.charAt(start - 1))) start--;
	const prefix = text.slice(start, quoteIndex);
	if (prefix.length === 0 || prefix.length > 3) return false;
	if (start > 0 && /[0-9_]/.test(text.charAt(start - 1))) return false;
	return /^[bBfFrRuU]+$/.test(prefix) && /[fF]/.test(prefix);
};
// Masks a string's interior in `masked`, starting just past its opening quote;
// returns the index just past its closing quote. For f-strings, `{` opens a
// replacement field (with `{{` as the literal-brace escape), which must be
// scanned rather than skipped: PEP 701 (Python 3.12) lets a field nest strings
// that reuse the enclosing quote, so stopping at the first matching quote
// would end the outer string early.
const maskStringInterior = (
	text: string,
	masked: string[],
	start: number,
	closer: string,
	isFString: boolean,
): number => {
	let position = start;
	while (position < text.length) {
		if (text[position] === "\\") {
			masked[position] = " ";
			if (position + 1 < text.length) masked[position + 1] = " ";
			position += 2;
			continue;
		}
		if (text.startsWith(closer, position)) return position + closer.length;
		if (isFString && text[position] === "{") {
			masked[position] = " ";
			if (text[position + 1] === "{") {
				masked[position + 1] = " ";
				position += 2;
				continue;
			}
			position = maskReplacementField(text, masked, position + 1);
			continue;
		}
		masked[position] = " ";
		position++;
	}
	return position;
};
// Masks a replacement field's contents from just past its `{` to just past its
// matching `}`, recursing into nested fields and nested string literals. The
// whole field is blanked: any parentheses inside it are balanced within the
// field, so hiding them keeps outer depth counts unchanged.
const maskReplacementField = (text: string, masked: string[], start: number): number => {
	let position = start;
	while (position < text.length) {
		const character = text[position];
		if (character === "}") {
			masked[position] = " ";
			return position + 1;
		}
		if (character === "{") {
			masked[position] = " ";
			position = maskReplacementField(text, masked, position + 1);
			continue;
		}
		if (character === '"' || character === "'") {
			const closer = text.startsWith(character.repeat(3), position)
				? character.repeat(3)
				: character;
			position = maskStringInterior(
				text,
				masked,
				position + closer.length,
				closer,
				isFStringOpener(text, position),
			);
			continue;
		}
		masked[position] = " ";
		position++;
	}
	return position;
};
// Length-preserving copy of Python source with every string-literal character
// and trailing `#` comment replaced by a space, so parenthesis counting and
// pattern matching see only code structure. Indices into the masked text line
// up with the original, and quote characters stay visible so a blanked string
// interior cannot read as an empty call argument. Handles both quote
// characters, triple-quoted forms, backslash escapes, and f-string
// replacement-field nesting (see maskStringInterior). Accepted bounded
// approximation: a `#` comment inside a multi-line replacement field is
// treated as expression text, because `#` is also a format-spec character
// (`{value:#x}`) and must not swallow the rest of the line there.
const maskStringsAndComments = (text: string): string => {
	const masked = text.split("");
	let position = 0;
	while (position < text.length) {
		const character = text[position];
		if (character === "#") {
			while (position < text.length && text[position] !== "\n") {
				masked[position] = " ";
				position++;
			}
			continue;
		}
		if (character === '"' || character === "'") {
			const closer = text.startsWith(character.repeat(3), position)
				? character.repeat(3)
				: character;
			position = maskStringInterior(
				text,
				masked,
				position + closer.length,
				closer,
				isFStringOpener(text, position),
			);
			continue;
		}
		position++;
	}
	return masked.join("");
};
// Parenthesis depth at `index`, counting from the start of the signature text.
// Top-level parameters sit at depth 1 (inside the def's own parentheses); a match
// at depth 2+ is a keyword argument inside a call expression. Callers pass text
// already run through maskStringsAndComments so quoted parentheses don't count.
const parenthesisDepthAt = (text: string, index: number): number => {
	let depth = 0;
	for (let position = 0; position < index; position++) {
		const character = text[position];
		if (character === "(") depth++;
		else if (character === ")") depth--;
	}
	return depth;
};
const RANGE_LEN_LOOP_RE =
	/^\s*for\s+([A-Za-z_]\w*)\s+in\s+range\s*\(\s*len\s*\(\s*([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*\)\s*\)\s*:\s*(?:#.*)?$/;
const CHAINED_DICT_GET_RE = /\.get\s*\([^)]*,\s*\{\s*\}\s*\)\s*\.get\s*\(/;
const SAME_VALUE_BRANCH_RE =
	/^(\s*)(?:if|elif)\s+([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*==\s*["'][^"']+["']\s*:/;
const INSTANCE_BRANCH_RE = /^(\s*)(?:if|elif)\s+isinstance\s*\(\s*([A-Za-z_]\w*)\s*,\s*[^)]+\)\s*:/;
const BRANCH_LADDER_THRESHOLD = 4;

const isTestFile = (relPath: string, basename: string): boolean =>
	basename.startsWith("test_") ||
	basename.endsWith("_test.py") ||
	basename === "conftest.py" ||
	relPath.split("/").some((seg) => seg === "tests" || seg === "test");

const isScriptOrEntrypoint = (basename: string): boolean =>
	basename === "__main__.py" || basename === "manage.py" || basename === "setup.py";

const SCRIPT_DIR_NAMES = new Set([
	"scripts",
	"bin",
	".github",
	"action",
	"docs",
	"docs_src",
	"examples",
	"example",
]);

const isInScriptDir = (relPath: string): boolean =>
	relPath.split("/").some((seg) => SCRIPT_DIR_NAMES.has(seg));

// Documentation/tutorial files in Python projects use print() to demonstrate output.
const isTutorialFile = (basename: string): boolean =>
	basename.startsWith("tutorial") && basename.endsWith(".py");

const MAIN_GUARD_RE = /^\s*if\s+__name__\s*==\s*["']__main__["']\s*:/;
const hasMainGuard = (lines: string[]): boolean => lines.some((l) => MAIN_GUARD_RE.test(l));

interface FlagArgs {
	relPath: string;
	rule: string;
	severity: "warning" | "error" | "info";
	message: string;
	help: string;
	line: number;
}

const pushFinding = (out: Diagnostic[], a: FlagArgs): void => {
	out.push({
		filePath: a.relPath,
		engine: "ai-slop",
		rule: a.rule,
		severity: a.severity,
		message: a.message,
		help: a.help,
		line: a.line,
		column: 1,
		category: "AI Slop",
		fixable: false,
	});
};

type FindingTemplate = Omit<FlagArgs, "relPath" | "line">;

const pushLineFinding = (
	out: Diagnostic[],
	relPath: string,
	line: number,
	finding: FindingTemplate,
): void => {
	pushFinding(out, { relPath, line, ...finding });
};

const flagBareExcept = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (!BARE_EXCEPT_RE.test(lines[i])) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-bare-except",
			severity: "warning",
			message:
				"Bare `except:` swallows every exception including KeyboardInterrupt and SystemExit.",
			help: "Catch the specific exception type you actually expect (`except ValueError:`, `except (KeyError, IndexError):`). If you genuinely want everything, `except BaseException:` plus a re-raise or log makes the intent explicit.",
			line: i + 1,
		});
	}
};

const flagBroadExceptWithSilentBody = (
	lines: string[],
	relPath: string,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const match = BROAD_EXCEPT_RE.exec(lines[i]);
		if (!match) continue;
		const next = lines[i + 1] ?? "";
		const trimmedNext = next.trim();
		// Quiet body == only `pass` or only a comment, with nothing else inside the suite.
		const isSilent =
			trimmedNext === "pass" ||
			(trimmedNext.startsWith("#") && (lines[i + 2] ?? "").trim() === "pass");
		if (!isSilent) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-broad-except",
			severity: "warning",
			message: `\`except ${match[1]}: pass\` silently drops every exception. Failures vanish without a trace.`,
			help: "Either narrow the exception class (`except ValueError:`), log the error, or re-raise. If you genuinely intend to swallow, add a comment naming the specific failure mode you're handling — auditors will thank you.",
			line: i + 1,
		});
	}
};

const flagMutableDefaults = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	let i = 0;
	while (i < lines.length) {
		if (!DEF_RE.test(lines[i])) {
			i++;
			continue;
		}
		// Walk forward until the signature closes (balanced parens over the
		// masked text, so parentheses inside strings or trailing comments
		// don't hold the walk open or close it early). Re-masking the whole
		// accumulated signature each iteration keeps triple-quoted strings
		// that span lines masked correctly; signatures are a handful of lines,
		// so the repeated pass costs nothing.
		const startLine = i;
		let signature = lines[i];
		let maskedSignature = maskStringsAndComments(signature);
		while (
			parenthesisDepthAt(maskedSignature, maskedSignature.length) > 0 &&
			i + 1 < lines.length
		) {
			i++;
			signature += `\n${lines[i]}`;
			maskedSignature = maskStringsAndComments(signature);
		}
		let found: RegExpMatchArray | null = null;
		// Matching against the masked signature also drops lookalike text inside
		// string defaults; a genuine match contains no string characters, so its
		// captures read identically from masked and raw text.
		for (const match of maskedSignature.matchAll(MUTABLE_DEFAULT_RE)) {
			// A mutable literal appearing as a keyword argument inside a call
			// (an empty dict handed to FastAPI's Body()/Query(), an empty list
			// handed to typer.Option()) is not the shared-mutable-default
			// footgun: the wrapper decides the value's lifetime, and FastAPI
			// and friends build a fresh value per request. Only a bare default
			// at the signature's top level aliases one object across every call.
			if (parenthesisDepthAt(maskedSignature, match.index ?? 0) > 1) continue;
			found = match;
			break;
		}
		if (found) {
			pushFinding(out, {
				relPath,
				rule: "ai-slop/python-mutable-default",
				severity: "warning",
				message: `Mutable default argument \`${found[1]}=${found[2]}\`. The default is shared across all calls — bugs that look like state-leakage.`,
				help: "Use `None` as the default and create the mutable value inside the body: `def f(items=None): items = items if items is not None else []`. Standard Python idiom; anything else is the AI agent shortcutting.",
				line: startLine + 1,
			});
		}
		i++;
	}
};

const flagPrintInProduction = (
	lines: string[],
	relPath: string,
	basename: string,
	out: Diagnostic[],
): void => {
	if (isTestFile(relPath, basename) || isScriptOrEntrypoint(basename)) return;
	if (isInScriptDir(relPath)) return;
	if (isTutorialFile(basename)) return;
	// Files with a main-guard treat their print() calls as CLI output, not debug residue.
	if (hasMainGuard(lines)) return;
	// String content is not executable, so any triple-quoted interior is
	// excluded here - not just docstring-positioned ones: a print() line inside
	// an assigned template string is template text, not debug residue.
	const stringContentLines = scanPythonDocstrings(lines).tripleQuotedStringLines;
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (!PRINT_RE.test(line)) continue;
		const trimmed = line.trim();
		if (trimmed.startsWith("#")) continue;
		if (stringContentLines.has(i)) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-print-debug",
			severity: "warning",
			message: "`print()` in production code — usually a leftover debug statement.",
			help: "Use the project's logger (`logging.getLogger(__name__).info(...)`). If this file is genuinely a CLI entry point (typer/click/argparse), it's safe to ignore — but rename to `__main__.py` or move under `scripts/` so the rule skips it next time.",
			line: i + 1,
		});
	}
};

const flagRangeLenLoops = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const match = RANGE_LEN_LOOP_RE.exec(lines[i]);
		if (!match) continue;
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-range-len-loop",
			severity: "info",
			message: `\`range(len(${match[2]}))\` loop — usually a hand-rolled iteration pattern.`,
			help: "Prefer direct iteration (`for item in items`) or `enumerate(items)` when the index is needed. Keeping index plumbing out of the loop reduces checkpoint-to-checkpoint bloat.",
		});
	}
};

const flagChainedDictGets = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (!CHAINED_DICT_GET_RE.test(lines[i])) continue;
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-chained-dict-get",
			severity: "warning",
			message: "Chained `.get(..., {})` defaults hide missing-data cases.",
			help: "Normalize the input at the boundary, use a typed object, or split the lookup into explicit steps. Empty-dict fallback chains are a common agent shortcut that becomes brittle as schemas evolve.",
		});
	}
};

const countBranchLadder = (
	lines: string[],
	start: number,
	pattern: RegExp,
	selector: string,
	indent: string,
): number => {
	let count = 1;
	for (let i = start + 1; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed === "" || trimmed.startsWith("#")) continue;
		const match = pattern.exec(line);
		if (match?.[1] === indent && match[2] === selector) {
			count++;
			continue;
		}
		if (line.startsWith(`${indent}elif `)) break;
		if (
			line.length - line.trimStart().length <= indent.length &&
			!line.startsWith(`${indent}else`)
		) {
			break;
		}
	}
	return count;
};

const flagBranchLadders = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	const reported = new Set<number>();
	for (let i = 0; i < lines.length; i++) {
		if (reported.has(i)) continue;
		const valueMatch = SAME_VALUE_BRANCH_RE.exec(lines[i]);
		if (valueMatch) {
			const count = countBranchLadder(lines, i, SAME_VALUE_BRANCH_RE, valueMatch[2], valueMatch[1]);
			if (count >= BRANCH_LADDER_THRESHOLD) {
				reported.add(i);
				pushLineFinding(out, relPath, i + 1, {
					rule: "ai-slop/python-repetitive-dispatch",
					severity: "warning",
					message: `${count} repeated branches dispatch on \`${valueMatch[2]}\`.`,
					help: "Use a table, set membership, or handler map when branches share the same shape. SlopCodeBench highlights these selector ladders as code that keeps growing instead of absorbing new cases cleanly.",
				});
			}
			continue;
		}

		const instanceMatch = INSTANCE_BRANCH_RE.exec(lines[i]);
		if (!instanceMatch) continue;
		const count = countBranchLadder(
			lines,
			i,
			INSTANCE_BRANCH_RE,
			instanceMatch[2],
			instanceMatch[1],
		);
		if (count < BRANCH_LADDER_THRESHOLD) continue;
		reported.add(i);
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-isinstance-ladder",
			severity: "warning",
			message: `${count} repeated \`isinstance(${instanceMatch[2]}, ...)\` branches.`,
			help: "Prefer a handler map, protocol, or normalized intermediate representation when each type branch has the same role. Repeated type ladders are one of the maintainability smells SCBench-style checks look for.",
		});
	}
};

export const detectPythonPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!PY_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = relativePosix(context.rootDirectory, filePath);
		const basename = path.basename(filePath);
		const lines = content.split("\n");

		flagBareExcept(lines, relPath, diagnostics);
		flagBroadExceptWithSilentBody(lines, relPath, diagnostics);
		flagMutableDefaults(lines, relPath, diagnostics);
		flagPrintInProduction(lines, relPath, basename, diagnostics);
		flagRangeLenLoops(lines, relPath, diagnostics);
		flagChainedDictGets(lines, relPath, diagnostics);
		flagBranchLadders(lines, relPath, diagnostics);
	}

	return diagnostics;
};
