export const PYTHON_IMPORT_TO_PIP: Record<string, string[]> = {
	yaml: ["pyyaml"],
	PIL: ["pillow"],
	dateutil: ["python-dateutil"],
	cv2: ["opencv-python", "opencv-python-headless", "opencv-contrib-python"],
	sklearn: ["scikit-learn"],
	bs4: ["beautifulsoup4"],
	typing_extensions: ["typing-extensions"],
	dotenv: ["python-dotenv"],
	genai: ["google-genai"],
	google: [
		"google-genai",
		"google-generativeai",
		"google-api-python-client",
		"google-cloud-storage",
		"google-cloud-aiplatform",
		"google-auth",
		"protobuf",
	],
	jose: ["python-jose"],
	jwt: ["pyjwt"],
	starlette: ["starlette", "fastapi"],
	asgiref: ["asgiref", "django"],
	OpenSSL: ["pyopenssl"],
	Crypto: ["pycryptodome", "pycryptodomex"],
	Cryptodome: ["pycryptodomex", "pycryptodome"],
	magic: ["python-magic"],
	docx: ["python-docx"],
	pptx: ["python-pptx"],
	git: ["gitpython"],
	github: ["pygithub"],
	socks: ["pysocks"],
	psycopg2: ["psycopg2-binary", "psycopg2"],
	redis: ["redis"],
	cairo: ["pycairo"],
	serial: ["pyserial"],
	usb: ["pyusb"],
	gi: ["pygobject"],
	Xlib: ["python-xlib"],
	ldap: ["python-ldap"],
	slugify: ["python-slugify"],
	memcache: ["python-memcached"],
	dns: ["dnspython"],
	attr: ["attrs"],
	attrs: ["attrs"],
	zoneinfo_data: ["tzdata"],
	pkg_resources: ["setuptools"],
	setuptools: ["setuptools"],
	wx: ["wxpython"],
	skimage: ["scikit-image"],
	OpenGL: ["pyopengl"],
	win32api: ["pywin32"],
	win32con: ["pywin32"],
	win32com: ["pywin32"],
	pythoncom: ["pywin32"],
	pywintypes: ["pywin32"],
	rest_framework: ["djangorestframework"],
	allauth: ["django-allauth"],
	corsheaders: ["django-cors-headers"],
	debug_toolbar: ["django-debug-toolbar"],
	environ: ["django-environ"],
	flask_cors: ["flask-cors"],
	flask_sqlalchemy: ["flask-sqlalchemy"],
	flask_migrate: ["flask-migrate"],
	flask_login: ["flask-login"],
	jwt_extended: ["flask-jwt-extended"],
	dateparser: ["dateparser"],
	yaml_include: ["pyyaml-include"],
	lxml_html_clean: ["lxml-html-clean"],
	grpc: ["grpcio"],
	grpc_status: ["grpcio-status"],
	google_crc32c: ["google-crc32c"],
	pkg_about: ["pkg-about"],
	mpl_toolkits: ["matplotlib"],
	dotmap: ["dotmap"],
	pydantic_settings: ["pydantic-settings"],
	telegram: ["python-telegram-bot"],
	discord: ["discord-py"],
	nacl: ["pynacl"],
	jwcrypto: ["jwcrypto"],
	humanfriendly: ["humanfriendly"],
	multipart: ["python-multipart"],
	paddle: ["paddlepaddle"],
	langchain_core: ["langchain-core", "langchain", "langchain-community"],
	langchain_community: ["langchain-community"],
	langchain_text_splitters: ["langchain-text-splitters"],
	huggingface_hub: ["huggingface-hub"],
	markdown_it: ["markdown-it-py"],
	cron_descriptor: ["cron-descriptor"],
	email_validator: ["email-validator"],
	e2b_code_interpreter: ["e2b-code-interpreter"],
	phonenumber_field: ["django-phonenumber-field"],
	frontmatter: ["python-frontmatter"],
	opentelemetry: ["opentelemetry-api", "opentelemetry-sdk"],
	ag_ui: ["ag-ui-protocol"],
};
