import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const RUST_EXTENSIONS = new Set([".rs"]);

const UNWRAP_CALL_RE = /\.unwrap\s*\(\s*\)/;
const TODO_MACRO_RE = /\b(todo|unimplemented)\s*!\s*\(/;
const COMMENT_LINE_RE = /^\s*\/\//;
const TEST_ATTR_RE = /^\s*#\s*\[\s*(?:cfg\s*\(\s*test\s*\)|test|tokio::test)/;
// `writeln!/write!(...).unwrap()` is infallible on String/Vec/Formatter writers.
const WRITELN_UNWRAP_RE = /\b(?:writeln|write)\s*!\s*\([^)]*\)\s*\.unwrap\s*\(\s*\)/;

const TEST_BASENAMES = new Set([
	"tests.rs",
	"testutil.rs",
	"test_util.rs",
	"test_utils.rs",
	"build.rs",
]);

const TEST_CRATE_SEGMENT_RE = /(?:^|[-_])tests?(?:$|[-_])/;

const isTestFile = (relPath: string): boolean => {
	const segments = relPath.split("/");
	if (segments.some((s) => TEST_CRATE_SEGMENT_RE.test(s))) return true;
	const basename = segments[segments.length - 1] ?? "";
	if (TEST_BASENAMES.has(basename)) return true;
	return (
		basename.endsWith("_tests.rs") ||
		basename.endsWith("_test.rs") ||
		basename.endsWith("_testutil.rs")
	);
};

const buildBlockCommentRanges = (lines: string[]): Array<[number, number]> => {
	const ranges: Array<[number, number]> = [];
	let openLine = -1;
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (openLine === -1) {
			const openIdx = line.indexOf("/*");
			if (openIdx !== -1 && line.indexOf("*/", openIdx + 2) === -1) {
				openLine = i;
			}
		} else if (line.indexOf("*/") !== -1) {
			ranges.push([openLine, i]);
			openLine = -1;
		}
	}
	if (openLine !== -1) ranges.push([openLine, lines.length - 1]);
	return ranges;
};

const isExampleFile = (relPath: string): boolean =>
	relPath.split("/").some((seg) => seg === "examples" || seg === "benches");

const UNWRAP_INTENT_LOOKBACK = 2;
const hasIntentComment = (lines: string[], lineIdx: number): boolean => {
	for (let j = lineIdx - 1; j >= Math.max(0, lineIdx - UNWRAP_INTENT_LOOKBACK); j--) {
		if (COMMENT_LINE_RE.test(lines[j])) return true;
	}
	return false;
};

// Walk the file: track whether we're inside a `#[cfg(test)]` mod block. Lines inside
// that block (or inside any `#[test]`-attributed item) are exempt from unwrap noise.
const buildTestRanges = (lines: string[]): Array<[number, number]> => {
	const ranges: Array<[number, number]> = [];
	for (let i = 0; i < lines.length; i++) {
		if (!TEST_ATTR_RE.test(lines[i])) continue;
		// Find the next `{` and walk to its matching `}`.
		const openLine = i;
		let depth = 0;
		let started = false;
		for (let j = i; j < lines.length; j++) {
			const line = lines[j];
			for (const ch of line) {
				if (ch === "{") {
					depth++;
					started = true;
				} else if (ch === "}") depth--;
			}
			if (started && depth === 0) {
				ranges.push([openLine, j]);
				i = j;
				break;
			}
		}
	}
	return ranges;
};

const isInRange = (ranges: Array<[number, number]>, lineIdx: number): boolean =>
	ranges.some(([start, end]) => lineIdx >= start && lineIdx <= end);

const flagNonTestUnwrap = (
	lines: string[],
	relPath: string,
	testRanges: Array<[number, number]>,
	blockCommentRanges: Array<[number, number]>,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (COMMENT_LINE_RE.test(line)) continue;
		if (isInRange(testRanges, i)) continue;
		if (isInRange(blockCommentRanges, i)) continue;
		if (!UNWRAP_CALL_RE.test(line)) continue;
		if (WRITELN_UNWRAP_RE.test(line)) continue;
		if (hasIntentComment(lines, i)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/rust-non-test-unwrap",
			severity: "warning",
			message:
				"`.unwrap()` in non-test code panics on None/Err. Surfaces as a hard crash for the caller.",
			help: 'Use `?` to propagate, `.expect("context")` if you really mean it (and the message names the invariant), or pattern-match the variant you care about. Reserve raw `.unwrap()` for tests and prototypes.',
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

const flagTodoMacro = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (COMMENT_LINE_RE.test(line)) continue;
		const match = TODO_MACRO_RE.exec(line);
		if (!match) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/rust-todo-stub",
			severity: "warning",
			message: `\`${match[1]}!()\` panics at runtime — almost certainly a stub the agent forgot to fill in.`,
			help: "Implement the missing path or remove it. If the work is genuinely deferred, file a ticket and put the number in a comment next to the macro so it doesn't ship invisibly.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

export const detectRustPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!RUST_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = relativePosix(context.rootDirectory, filePath);
		const lines = content.split("\n");

		// Examples are pedagogical — `.unwrap()` and `todo!()` are routine teaching shorthand.
		if (isExampleFile(relPath)) continue;

		// Whole-file test mode: skip unwrap-checking, still flag todo!() (those are bugs anywhere).
		if (isTestFile(relPath)) {
			flagTodoMacro(lines, relPath, diagnostics);
			continue;
		}

		const testRanges = buildTestRanges(lines);
		const blockCommentRanges = buildBlockCommentRanges(lines);
		flagNonTestUnwrap(lines, relPath, testRanges, blockCommentRanges, diagnostics);
		flagTodoMacro(lines, relPath, diagnostics);
	}

	return diagnostics;
};
