import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JS_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const CATCH_HEAD_RE = /\bcatch\s*(?:\(\s*([^)]*?)\s*\))?\s*\{/g;

const isIdentifier = (s: string): boolean => /^[A-Za-z_$][\w$]*$/.test(s);

// Logging the caught error is observable recovery; only a dropped error is a silent swallow.
const recoveryDropsError = (binding: string | undefined, body: string): boolean => {
	const name = binding?.trim() ?? "";
	if (name === "") return true;
	if (!isIdentifier(name)) return false; // destructured/aliased binding keeps the detail
	return !new RegExp(`\\b${name}\\b`).test(body);
};

// A statement that only emits a log line: console.* or <ident>.{warn,info,error,log,debug}(...).
const LOG_STATEMENT_RE =
	/^(?:console|[\w$]+(?:\.[\w$]+)*)\.(?:log|info|warn|warning|error|debug|trace)\s*\(/;

// Control-flow / handling tokens that mean the catch does more than log-and-continue.
const HANDLING_TOKEN_RE = /\b(?:throw|return|reject|next|process\.exit|continue|break)\b/;

const stripBlockComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//g, "");

const extractCatchBody = (content: string, openBraceIndex: number): string | null => {
	let depth = 0;
	let inString: string | null = null;
	for (let i = openBraceIndex; i < content.length; i += 1) {
		const ch = content[i];
		const prev = content[i - 1];
		if (inString) {
			if (ch === inString && prev !== "\\") inString = null;
			continue;
		}
		if (ch === '"' || ch === "'" || ch === "`") {
			inString = ch;
			continue;
		}
		if (ch === "{") {
			depth += 1;
		} else if (ch === "}") {
			depth -= 1;
			if (depth === 0) return content.slice(openBraceIndex + 1, i);
		}
	}
	return null;
};

// True when every statement in the body is a bare log call and nothing else.
const isLogOnlyBody = (body: string): boolean => {
	const cleaned = stripBlockComments(body);
	const statements = cleaned
		.split("\n")
		.map((line) => line.replace(/\/\/.*$/, "").trim())
		.filter((line) => line.length > 0 && line !== ";");

	if (statements.length === 0) return false; // empty catch is swallowed-exception's job.
	if (statements.some((line) => HANDLING_TOKEN_RE.test(line))) return false;

	let sawLog = false;
	for (const statement of statements) {
		// Allow trailing semicolons and a lone closing/opening artifact from multi-line calls.
		const normalized = statement.replace(/;+$/, "");
		if (LOG_STATEMENT_RE.test(normalized)) {
			sawLog = true;
			continue;
		}
		// A continuation line of a multi-line log call (arguments only) is acceptable.
		if (/^[\w$"'`{[(),.\s+:-]+$/.test(normalized) && !/[=(]\s*(?:async\s+)?\(/.test(normalized)) {
			continue;
		}
		return false;
	}
	return sawLog;
};

const detectJsSilentRecovery = (content: string, relPath: string): Diagnostic[] => {
	const out: Diagnostic[] = [];
	for (const match of content.matchAll(CATCH_HEAD_RE)) {
		const braceIndex = match.index + match[0].length - 1;
		const body = extractCatchBody(content, braceIndex);
		if (body === null) continue;
		if (!isLogOnlyBody(body)) continue;
		if (!recoveryDropsError(match[1], body)) continue;

		const line = content.slice(0, match.index).split("\n").length;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/silent-recovery",
			severity: "warning",
			message: "Catch logs without the caught error then continues; the failure cause is lost",
			help: "Include the caught error in the log, or rethrow / recover explicitly, so the failure stays diagnosable.",
			line,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return out;
};

const PY_EXCEPT_RE = /^(\s*)except\b[^\n]*:\s*(?:#.*)?$/;
const PY_EXCEPT_BINDING_RE = /\bas\s+(\w+)\s*:/;
const PY_LOG_STATEMENT_RE =
	/^(?:logging|logger|log|self\.log|self\.logger|print)(?:\.(?:debug|info|warning|warn|error|exception|critical))?\s*\(/;
const PY_HANDLING_TOKEN_RE = /^(?:raise\b|return\b|continue\b|break\b|self\.|[\w.]+\s*=)/;
// `logging.Logger.exception(...)` defaults to attaching the currently-handled
// exception's traceback (it is `.error(..., exc_info=True)`), and `exc_info=True` on any
// logging call does the same explicitly. Either one means the failure cause is
// captured even though no `except ... as <name>` identifier appears in the log call.
const PY_LOG_CAPTURES_EXCEPTION_RE = /\.exception\s*\(|\bexc_info\s*=\s*True\b/;
// `.exception(..., exc_info=False)` forwards that value to `Logger.error` and drops the
// traceback, so the literal spelling anywhere in the same call cancels the exemption. Only the
// literal `False` is recognized; an `exc_info` set to anything else stays exempt rather
// than guessed at.
const PY_EXC_INFO_DISABLED_RE = /\bexc_info\s*=\s*False\b/;

type PyStatement = { text: string; masked: string };

// Python continues a call while a bracket is open and separates simple statements with
// `;`, so a raw line is neither reliably one statement nor a whole one. Reading them
// per line split a call into fragments, and `exc_info=False,` alone on a line matched
// the assignment pattern that marks a handler as doing real work.
// `masked` blanks string bodies and comments so prose cannot satisfy a keyword check;
// `text` keeps them, since an f-string is a real reference to the bound exception.
const splitPyStatements = (bodyLines: string[]): PyStatement[] => {
	const statements: PyStatement[] = [];
	let text = "";
	let masked = "";
	let depth = 0;
	let quote: string | null = null;

	const flush = (): void => {
		if (text.trim() !== "") statements.push({ text: text.trim(), masked: masked.trim() });
		text = "";
		masked = "";
	};

	for (const line of bodyLines) {
		if (text !== "") {
			text += " ";
			masked += " ";
		}

		let i = 0;
		while (i < line.length) {
			if (quote !== null) {
				const closes = line.startsWith(quote, i);
				const width = line[i] === "\\" ? 2 : closes ? quote.length : 1;
				text += line.slice(i, i + width);
				if (closes) {
					masked += quote;
					quote = null;
				}
				i += width;
				continue;
			}

			const ch = line[i];
			if (ch === "#") {
				text += line.slice(i);
				break;
			}
			if (ch === '"' || ch === "'") {
				quote = line.startsWith(ch.repeat(3), i) ? ch.repeat(3) : ch;
				text += quote;
				masked += quote;
				i += quote.length;
				continue;
			}
			if (ch === ";" && depth === 0) {
				flush();
				i += 1;
				continue;
			}

			text += ch;
			masked += ch;
			if (ch === "(" || ch === "[" || ch === "{") depth += 1;
			else if (ch === ")" || ch === "]" || ch === "}") depth = Math.max(0, depth - 1);
			i += 1;
		}

		// A single-quoted string cannot span a line break, so one still open at the end of
		// the line means the scan misread it rather than that the statement continues.
		if (quote !== null && quote.length === 1) quote = null;
		if (depth === 0 && quote === null && !line.endsWith("\\")) flush();
	}
	flush();

	return statements;
};

const pyLogStatementCapturesException = (statement: string): boolean =>
	PY_LOG_CAPTURES_EXCEPTION_RE.test(statement) && !PY_EXC_INFO_DISABLED_RE.test(statement);

const detectPySilentRecovery = (content: string, relPath: string): Diagnostic[] => {
	const out: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i += 1) {
		const exceptMatch = PY_EXCEPT_RE.exec(lines[i]);
		if (!exceptMatch) continue;
		const indent = exceptMatch[1].length;

		const rawBodyLines: string[] = [];
		let j = i + 1;
		for (; j < lines.length; j += 1) {
			const raw = lines[j];
			if (raw.trim() === "") continue;
			const lineIndent = raw.length - raw.trimStart().length;
			if (lineIndent <= indent) break;
			rawBodyLines.push(raw.trim());
		}

		const body = splitPyStatements(rawBodyLines);
		if (body.length === 0) continue;
		if (body.some((s) => PY_HANDLING_TOKEN_RE.test(s.masked))) continue;
		if (body.some((s) => s.masked === "pass")) continue; // swallowed-exception's job.

		const allLogs = body.every(
			(s) => PY_LOG_STATEMENT_RE.test(s.masked) || /^[\w"'(),.\s+:%{}[\]-]+$/.test(s.masked),
		);
		const sawLog = body.some((s) => PY_LOG_STATEMENT_RE.test(s.masked));
		if (!allLogs || !sawLog) continue;
		if (body.some((s) => pyLogStatementCapturesException(s.masked))) continue;
		const bodyText = body.map((s) => s.text).join(" ");
		if (!recoveryDropsError(PY_EXCEPT_BINDING_RE.exec(lines[i])?.[1], bodyText)) continue;

		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/silent-recovery",
			severity: "warning",
			message: "except logs without the caught error then continues; the failure cause is lost",
			help: "Include the caught error in the log, or re-raise / recover explicitly, so the failure stays diagnosable.",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return out;
};

export const detectSilentRecovery = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		const ext = path.extname(filePath);
		const isJs = JS_EXTS.has(ext);
		const isPy = ext === ".py";
		if (!isJs && !isPy) continue;

		const relPath = relativePosix(context.rootDirectory, filePath);
		if (isNonProductionPath(relPath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		if (isJs) {
			diagnostics.push(...detectJsSilentRecovery(content, relPath));
		} else {
			diagnostics.push(...detectPySilentRecovery(content, relPath));
		}
	}

	return diagnostics;
};
