import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getTestFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskComments, maskStringsAndComments } from "../../utils/source-masker.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const EXPECT_NAME = "ex" + "pect";
const ASSERT_NAME = "as" + "sert";
const JS_LITERAL = String.raw`(?:true|false|null|undefined|-?\d+(?:\.\d+)?|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')`;
const JS_TAUTOLOGY_PATTERNS = [
	new RegExp(
		String.raw`\b${EXPECT_NAME}\s*\(\s*(${JS_LITERAL})\s*\)\s*\.\s*toBe\s*\(\s*(${JS_LITERAL})\s*\)`,
		"g",
	),
	new RegExp(
		String.raw`\b${ASSERT_NAME}\s*\.\s*(?:equal|strictEqual)\s*\(\s*(${JS_LITERAL})\s*,\s*(${JS_LITERAL})\s*\)`,
		"g",
	),
];
const PYTHON_TAUTOLOGY_RE = new RegExp(String.raw`^\s*${ASSERT_NAME}\s+True\s*$`);

type FixedLiteral = string | number | boolean | null | undefined;
const SIMPLE_STRING_ESCAPES: Readonly<Record<string, string>> = {
	b: "\b",
	f: "\f",
	n: "\n",
	r: "\r",
	t: "\t",
	v: "\v",
	"0": "\0",
};

const parseHexEscape = (value: string): string | null => {
	if (!/^[\da-f]+$/i.test(value)) return null;
	const codePoint = Number.parseInt(value, 16);
	if (codePoint > 0x10ffff) return null;
	return String.fromCodePoint(codePoint);
};

const parseStringLiteral = (rawValue: string): string | null => {
	let value = "";
	for (let index = 1; index < rawValue.length - 1; index++) {
		const character = rawValue[index];
		if (character !== "\\") {
			value += character;
			continue;
		}
		index++;
		if (index >= rawValue.length - 1) return null;
		const escapeCode = rawValue[index];
		if (SIMPLE_STRING_ESCAPES[escapeCode] !== undefined) {
			value += SIMPLE_STRING_ESCAPES[escapeCode];
			continue;
		}
		if (escapeCode === "x") {
			const decoded = parseHexEscape(rawValue.slice(index + 1, index + 3));
			if (decoded === null) return null;
			value += decoded;
			index += 2;
			continue;
		}
		if (escapeCode === "u") {
			const hasBraces = rawValue[index + 1] === "{";
			const end = hasBraces ? rawValue.indexOf("}", index + 2) : index + 5;
			if (end === -1 || end >= rawValue.length) return null;
			const digits = rawValue.slice(index + (hasBraces ? 2 : 1), end);
			if ((!hasBraces && digits.length !== 4) || digits.length === 0) return null;
			const decoded = parseHexEscape(digits);
			if (decoded === null) return null;
			value += decoded;
			index = hasBraces ? end : end - 1;
			continue;
		}
		value += escapeCode;
	}
	return value;
};

const parseFixedLiteral = (rawValue: string): { value: FixedLiteral } | null => {
	if (rawValue === "true") return { value: true };
	if (rawValue === "false") return { value: false };
	if (rawValue === "null") return { value: null };
	if (rawValue === "undefined") return { value: undefined };
	if (rawValue.startsWith('"') || rawValue.startsWith("'")) {
		const value = parseStringLiteral(rawValue);
		return value === null ? null : { value };
	}
	return { value: Number(rawValue) };
};

const literalsAreEqual = (left: string, right: string): boolean => {
	const leftLiteral = parseFixedLiteral(left);
	const rightLiteral = parseFixedLiteral(right);
	return !!leftLiteral && !!rightLiteral && Object.is(leftLiteral.value, rightLiteral.value);
};

const isTautologicalLine = (line: string, fullyMaskedLine: string, extension: string): boolean => {
	if (extension === ".py") return PYTHON_TAUTOLOGY_RE.test(fullyMaskedLine);
	if (!JS_EXTENSIONS.has(extension)) return false;
	return JS_TAUTOLOGY_PATTERNS.some((pattern) => {
		pattern.lastIndex = 0;
		let match = pattern.exec(line);
		while (match) {
			const name = match[0].startsWith(EXPECT_NAME) ? EXPECT_NAME : ASSERT_NAME;
			if (
				fullyMaskedLine.slice(match.index, match.index + name.length) === name &&
				literalsAreEqual(match[1], match[2])
			) {
				return true;
			}
			match = pattern.exec(line);
		}
		return false;
	});
};

export const detectTautologicalTests = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	for (const filePath of getTestFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const extension = path.extname(filePath).toLowerCase();
		const lines = maskComments(content, extension).split("\n");
		const fullyMaskedLines = maskStringsAndComments(content, extension).split("\n");
		for (let index = 0; index < lines.length; index++) {
			if (!isTautologicalLine(lines[index], fullyMaskedLines[index], extension)) continue;
			diagnostics.push({
				filePath: relativePosix(context.rootDirectory, filePath),
				engine: "ai-slop",
				rule: "ai-slop/tautological-test",
				severity: "warning",
				message: "Tautological test assertion cannot fail",
				help: "Assert behavior produced by the code under test instead of comparing fixed literals.",
				line: index + 1,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}
	return diagnostics;
};
