import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFilesWithExtras, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

// Stylesheets we parse for class *definitions*.
const STYLE_EXTENSIONS = new Set([".css", ".scss"]);
// Files we scan for class *references*. CSS itself is included so `@apply`,
// `composes`, and selectors that combine classes count as references.
const REFERENCE_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".mjs",
	".cjs",
	".astro",
	".vue",
	".svelte",
	".html",
	".htm",
	".php",
	".erb",
	".md",
	".mdx",
	".css",
	".scss",
]);

// Extra extensions the file walker must surface (beyond its built-in source set).
const UNUSED_CSS_EXTRA_EXTENSIONS = [
	".css",
	".scss",
	".astro",
	".vue",
	".svelte",
	".html",
	".htm",
	".erb",
	".md",
	".mdx",
];

interface ClassDefinition {
	name: string;
	line: number;
}

// Strip /* ... */ comments so commented-out rules don't register as definitions.
const stripCssComments = (content: string): string => content.replace(/\/\*[\s\S]*?\*\//g, "");

// A class token in a selector: `.foo`, `.foo-bar`, `.foo__bar--baz`.
// We deliberately ignore pseudo-classes (`:hover`) and attribute selectors.
const SELECTOR_CLASS_RE = /\.(-?[A-Za-z_][\w-]*)/g;

// Tailwind / utility-class signatures. These are framework-generated or utility
// names that authors don't "own", so flagging them as dead would be noise and
// risks deleting framework styles. Conservative by design: when unsure, skip.
const TAILWIND_PREFIXES = [
	"sm:",
	"md:",
	"lg:",
	"xl:",
	"2xl:",
	"hover:",
	"focus:",
	"active:",
	"group-",
	"peer-",
	"dark:",
	"motion-",
	"first:",
	"last:",
	"odd:",
	"even:",
	"disabled:",
];

const TAILWIND_UTILITY_RE =
	/^(?:m|p)(?:[trblxy])?-(?:\d|px|auto|\[)|^(?:w|h|min-w|min-h|max-w|max-h)-|^(?:text|bg|border|ring|from|via|to|fill|stroke)-(?:\[|(?:red|blue|green|gray|grey|slate|zinc|neutral|stone|amber|yellow|lime|emerald|teal|cyan|sky|indigo|violet|purple|fuchsia|pink|rose|orange|white|black|transparent|current)\b)|^(?:flex|grid|gap|space|inset|top|bottom|left|right|z|order|col|row|justify|items|content|self|place)-|^(?:rounded|shadow|opacity|leading|tracking|font|duration|delay|ease|translate|scale|rotate|skew|origin|cursor|select|overflow|object|aspect|columns|divide|backdrop|blur|brightness|contrast|grayscale|saturate|sepia)-/;

const looksLikeTailwindUtility = (name: string): boolean => {
	if (TAILWIND_PREFIXES.some((prefix) => name.includes(prefix))) return true;
	if (TAILWIND_UTILITY_RE.test(name)) return true;
	// Arbitrary-value utilities like `top-[3px]` or fraction utilities `w-1/2`.
	if (name.includes("[") || name.includes("/")) return true;
	// Standalone single-purpose utilities Tailwind ships without a value segment.
	if (
		/^(?:flex|grid|block|inline|hidden|table|contents|container|relative|absolute|fixed|sticky|static|truncate|italic|underline|uppercase|lowercase|capitalize|antialiased|sr-only)$/.test(
			name,
		)
	) {
		return true;
	}
	return false;
};

const collectClassDefinitions = (content: string): ClassDefinition[] => {
	const stripped = stripCssComments(content);
	const lines = stripped.split("\n");
	const seen = new Set<string>();
	const definitions: ClassDefinition[] = [];

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		// Only treat text on a line that opens or continues a selector block as a
		// selector. A line containing an open brace very likely holds the selector; lines that
		// are pure declarations (`color: red;`) contain no `.class` tokens anyway,
		// but `.foo` inside a value (rare) is filtered by requiring it isn't a number.
		SELECTOR_CLASS_RE.lastIndex = 0;
		let match: RegExpExecArray | null = SELECTOR_CLASS_RE.exec(line);
		while (match !== null) {
			const name = match[1];
			// `.5` style decimals never match (must start with letter/_/-), but guard anyway.
			if (name && !seen.has(name)) {
				seen.add(name);
				definitions.push({ name, line: i + 1 });
			}
			match = SELECTOR_CLASS_RE.exec(line);
		}
	}

	return definitions;
};

// A class is "referenced" if its exact name appears anywhere in the combined
// reference corpus, OR if any hyphen-delimited prefix of it appears. The prefix
// rule is the key false-positive guard for dynamic class construction: a template
// literal like `ui-${kind}` only contains the literal `ui-`, so seeing `ui-` in
// the corpus must shield every `ui-*` class. We use raw substring matching on
// purpose — it also catches className strings, cn()/clsx() args, and data-* uses.
// Under-reporting beats deleting a live style.
const isReferenced = (name: string, corpus: string): boolean => {
	if (corpus.includes(name)) return true;
	// Build interpolation prefixes: "ui-toggle" -> ["ui-"]; "a-b-c" -> ["a-", "a-b-"].
	let cut = name.indexOf("-");
	while (cut !== -1) {
		if (corpus.includes(name.slice(0, cut + 1))) return true;
		cut = name.indexOf("-", cut + 1);
	}
	return false;
};

interface ScanInputs {
	styleFiles: string[];
	corpus: string;
}

const collectScanInputs = (files: string[]): ScanInputs => {
	const styleFiles: string[] = [];
	const referenceChunks: string[] = [];

	for (const filePath of files) {
		const ext = path.extname(filePath).toLowerCase();
		const isStyle = STYLE_EXTENSIONS.has(ext);
		const isReference = REFERENCE_EXTENSIONS.has(ext);
		if (!isStyle && !isReference) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		if (isStyle) styleFiles.push(filePath);
		if (isReference) {
			// For stylesheets, drop the selector tokens themselves from the corpus so a
			// class isn't considered "referenced" merely by its own definition. We keep
			// declaration bodies (which hold @apply/composes references).
			referenceChunks.push(isStyle ? stripSelectorTokens(content) : content);
		}
	}

	return { styleFiles, corpus: referenceChunks.join("\n") };
};

export const detectUnusedCss = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFilesWithExtras(context, UNUSED_CSS_EXTRA_EXTENSIONS);
	if (files.length === 0) return [];

	const { styleFiles, corpus } = collectScanInputs(files);
	if (styleFiles.length === 0) return [];

	const diagnostics: Diagnostic[] = [];

	for (const filePath of styleFiles) {
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relativePath = relativePosix(context.rootDirectory, filePath);
		const definitions = collectClassDefinitions(content);

		for (const def of definitions) {
			if (looksLikeTailwindUtility(def.name)) continue;
			if (isReferenced(def.name, corpus)) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/unused-css",
				severity: "warning",
				message: `CSS class '.${def.name}' is defined but never referenced in the codebase`,
				help: "Remove the dead CSS rule, or confirm the class is used dynamically (and add an aislop-ignore comment if so)",
				line: def.line,
				column: 0,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};

// Remove `.class` selector tokens from a stylesheet's text so that, when other
// stylesheets are folded into the reference corpus, a class's own selector does
// not count as a reference to it. Declaration bodies and @apply lines survive.
const stripSelectorTokens = (content: string): string => {
	const stripped = stripCssComments(content);
	return stripped
		.split("\n")
		.map((line) => {
			// Lines that look like selectors (no `:` declaration, end before `{`) get
			// their `.class` tokens blanked. We keep `@apply .foo;`-style references by
			// only blanking tokens on lines that contain `{` or comma-joined selectors.
			if (/@apply\b/.test(line)) return line;
			if (line.includes("{") || /^\s*\.[\w-]/.test(line) || /,\s*$/.test(line)) {
				return line.replace(SELECTOR_CLASS_RE, " ");
			}
			return line;
		})
		.join("\n");
};
