import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

export const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
export const PY_EXTENSIONS = new Set([".py"]);
export const REMOVE_MARKER = "\0__AISLOP_REMOVE__";

export interface ImportedSymbol {
	name: string;
	line: number;
	isDefault: boolean;
	isNamespace: boolean;
}

const extractJsImportedSymbols = (
	lines: string[],
): { symbols: ImportedSymbol[]; importLines: Set<number> } => {
	const symbols: ImportedSymbol[] = [];
	const importLines = new Set<number>();

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();

		if (!trimmed.startsWith("import ")) continue;

		importLines.add(i);

		if (/^import\s+["']/.test(trimmed)) continue;
		if (/^import\s+type\s/.test(trimmed)) continue;

		let fullImport = trimmed;
		let endLine = i;
		while (!fullImport.includes("from") && endLine < lines.length - 1) {
			endLine++;
			fullImport += ` ${lines[endLine].trim()}`;
			importLines.add(endLine);
		}

		const namespaceMatch = fullImport.match(/import\s+\*\s+as\s+(\w+)\s+from/);
		if (namespaceMatch) {
			symbols.push({
				name: namespaceMatch[1],
				line: i + 1,
				isDefault: false,
				isNamespace: true,
			});
			continue;
		}

		const defaultMatch = fullImport.match(/import\s+(\w+)\s*(?:,\s*\{[^}]*\})?\s+from/);
		if (defaultMatch && defaultMatch[1] !== "type") {
			symbols.push({
				name: defaultMatch[1],
				line: i + 1,
				isDefault: true,
				isNamespace: false,
			});
		}

		const namedMatch = fullImport.match(/\{([^}]+)\}/);
		if (namedMatch) {
			const namedImports = namedMatch[1].split(",");
			for (const ni of namedImports) {
				const parts = ni.trim().split(/\s+as\s+/);
				if (parts.length === 0 || !parts[0]) continue;
				const cleanParts = parts.map((p) => p.trim().replace(/^type\s+/, ""));
				const localName = cleanParts.length > 1 ? cleanParts[1] : cleanParts[0];
				if (localName && /^\w+$/.test(localName)) {
					symbols.push({
						name: localName,
						line: i + 1,
						isDefault: false,
						isNamespace: false,
					});
				}
			}
		}
	}

	return { symbols, importLines };
};

const extractPyImportedSymbols = (
	lines: string[],
): { symbols: ImportedSymbol[]; importLines: Set<number> } => {
	const symbols: ImportedSymbol[] = [];
	const importLines = new Set<number>();

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();

		const fromMatch = trimmed.match(/^from\s+([\w.]+)\s+import\s+(.+)/);
		if (fromMatch) {
			importLines.add(i);
			// `from __future__ import ...` is a parser directive, not a name that gets used.
			if (fromMatch[1] === "__future__") continue;
			const importPart = fromMatch[2].replace(/#.*$/, "").trim();
			if (importPart === "*") continue;
			const cleaned = importPart.replace(/[()]/g, "");
			for (const item of cleaned.split(",")) {
				const parts = item.trim().split(/\s+as\s+/);
				const original = parts[0].trim();
				const localName = parts.length > 1 ? parts[1].trim() : original;
				// PEP 484 re-export convention: `from X import Y as Y` explicitly publishes Y.
				if (parts.length > 1 && original === localName) continue;
				if (localName && /^\w+$/.test(localName)) {
					symbols.push({
						name: localName,
						line: i + 1,
						isDefault: false,
						isNamespace: false,
					});
				}
			}
			continue;
		}

		const importMatch = trimmed.match(/^import\s+(.+)/);
		if (importMatch) {
			importLines.add(i);
			// `import a, b.c as d` binds each comma-separated clause independently;
			// capturing only the first would delete the whole line for one unused name.
			for (const clause of importMatch[1].replace(/#.*$/, "").split(",")) {
				const clauseMatch = clause.trim().match(/^([\w.]+)(?:\s+as\s+(\w+))?/);
				if (!clauseMatch) continue;
				const alias = clauseMatch[2];
				// `import X as X` is a re-export marker.
				if (alias && alias === clauseMatch[1]) continue;
				const localName = alias ?? clauseMatch[1];
				const simpleName = localName.split(".")[0];
				if (simpleName && /^\w+$/.test(simpleName)) {
					symbols.push({
						name: simpleName,
						line: i + 1,
						isDefault: false,
						isNamespace: true,
					});
				}
			}
		}
	}

	return { symbols, importLines };
};

const isSymbolUsed = (
	name: string,
	content: string,
	importLines: Set<number>,
	lines: string[],
): boolean => {
	const pattern = new RegExp(`\\b${name}\\b`, "g");
	for (const match of content.matchAll(pattern)) {
		const lineIndex = content.slice(0, match.index).split("\n").length - 1;
		if (!importLines.has(lineIndex)) return true;
	}

	for (let i = 0; i < lines.length; i++) {
		if (importLines.has(i)) continue;
		if (lines[i].includes(name)) return true;
	}

	return false;
};

export const analyzeFile = (
	filePath: string,
): {
	lines: string[];
	symbols: ImportedSymbol[];
	importLines: Set<number>;
	ext: string;
} | null => {
	if (isAutoGenerated(filePath)) return null;
	let content: string;
	try {
		content = fs.readFileSync(filePath, "utf-8");
	} catch {
		return null;
	}

	const ext = path.extname(filePath);
	const lines = content.split("\n");

	let symbols: ImportedSymbol[];
	let importLines: Set<number>;

	if (JS_EXTENSIONS.has(ext)) {
		const result = extractJsImportedSymbols(lines);
		symbols = result.symbols;
		importLines = result.importLines;
	} else if (PY_EXTENSIONS.has(ext)) {
		const result = extractPyImportedSymbols(lines);
		symbols = result.symbols;
		importLines = result.importLines;
	} else {
		return null;
	}

	return { lines, symbols, importLines, ext };
};

export const getUnusedSymbols = (
	lines: string[],
	symbols: ImportedSymbol[],
	importLines: Set<number>,
): ImportedSymbol[] => {
	const content = lines.join("\n");
	return symbols.filter((symbol) => !isSymbolUsed(symbol.name, content, importLines, lines));
};

export const detectUnusedImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const analysis = analyzeFile(filePath);
		if (!analysis) continue;

		const relativePath = relativePosix(context.rootDirectory, filePath);
		const unused = getUnusedSymbols(analysis.lines, analysis.symbols, analysis.importLines);

		for (const symbol of unused) {
			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/unused-import",
				severity: "warning",
				message: `Imported symbol '${symbol.name}' is never used`,
				help: "Remove unused imports to keep the code clean",
				line: symbol.line,
				column: 0,
				category: "AI Slop",
				fixable: true,
			});
		}
	}

	return diagnostics;
};
