import { runSubprocess } from "../utils/subprocess.js";

interface AgentPublishOptions {
	commit: boolean;
	pr: boolean;
	branch?: string;
	base?: string;
	commitMessage: string;
	prTitle?: string;
	ready: boolean;
}

interface PublishAgentDiffInput {
	cwd: string;
	originalBranch: string | null;
	providerId: string;
	beforeScore: number | null;
	afterScore: number | null;
	changedFiles: string[];
	options: AgentPublishOptions;
}

export interface PublishAgentDiffResult {
	branch: string;
	commitSha: string;
	pushed: boolean;
	prUrl: string | null;
}

const defaultBranchSuffix = (): string =>
	new Date().toISOString().replace(/[-:]/g, "").replace(/\..+$/, "").replace("T", "-");

export const normalizeBranchName = (raw: string): string => {
	const cleaned = raw
		.trim()
		.replace(/[^A-Za-z0-9._/-]+/g, "-")
		.replace(/\/+/g, "/")
		.replace(/^-+|-+$/g, "")
		.replace(/^\/+|\/+$/g, "");
	return cleaned.length > 0 ? cleaned.slice(0, 120) : `aislop/agent-${defaultBranchSuffix()}`;
};

const defaultBranchName = (): string => `aislop/agent-${defaultBranchSuffix()}`;

const runGit = async (cwd: string, args: string[]): Promise<string> => {
	const result = await runSubprocess("git", args, { cwd, timeout: 90_000 });
	if (result.exitCode !== 0) {
		throw new Error(result.stderr || result.stdout || `git ${args.join(" ")} failed`);
	}
	return result.stdout;
};

const currentBranch = async (cwd: string): Promise<string | null> => {
	const result = await runSubprocess("git", ["branch", "--show-current"], { cwd });
	if (result.exitCode !== 0) return null;
	return result.stdout.trim() || null;
};

const resolveBaseBranch = async (cwd: string, fallback: string | null): Promise<string> => {
	const remote = await runSubprocess("git", ["remote", "show", "origin"], { cwd, timeout: 30_000 });
	if (remote.exitCode === 0) {
		const line = remote.stdout.split("\n").find((entry) => entry.trim().startsWith("HEAD branch:"));
		const branch = line?.split(":").slice(1).join(":").trim();
		if (branch) return branch;
	}
	return fallback ?? "main";
};

const ensureBranch = async (cwd: string, branch: string): Promise<void> => {
	if ((await currentBranch(cwd)) === branch) return;
	await runGit(cwd, ["switch", "-c", branch]);
};

const ensureGh = async (): Promise<void> => {
	const result = await runSubprocess("gh", ["--version"], { timeout: 10_000 });
	if (result.exitCode !== 0) {
		throw new Error(
			"Creating a PR requires the GitHub CLI. Install and authenticate `gh`, then retry.",
		);
	}
};

export const buildPrBody = (input: {
	providerId: string;
	beforeScore: number | null;
	afterScore: number | null;
	changedFiles: string[];
}): string => {
	const score = `${input.beforeScore ?? "not scored"} -> ${input.afterScore ?? "not scored"}`;
	return [
		"This PR was generated locally by `aislop agent`.",
		"",
		"## Summary",
		"",
		`- Provider: ${input.providerId}`,
		`- Score: ${score}`,
		`- Files changed: ${input.changedFiles.length}`,
		"",
		"## Changed files",
		"",
		...input.changedFiles.map((file) => `- ${file}`),
		"",
		"## Verification",
		"",
		"- `aislop scan --json`",
		"",
		"Review before merging. The deterministic scan is the gate; the provider only proposed the patch.",
	].join("\n");
};

export const publishAgentDiff = async (
	input: PublishAgentDiffInput,
): Promise<PublishAgentDiffResult | null> => {
	if (!input.options.commit && !input.options.pr) return null;
	if (input.changedFiles.length === 0) return null;

	const branch = normalizeBranchName(input.options.branch ?? defaultBranchName());
	await ensureBranch(input.cwd, branch);
	await runGit(input.cwd, ["add", "-A"]);
	const staged = await runSubprocess("git", ["diff", "--cached", "--quiet"], { cwd: input.cwd });
	if (staged.exitCode === 0) return null;

	await runGit(input.cwd, [
		"commit",
		"-m",
		input.options.commitMessage,
		"-m",
		"Generated by aislop agent.",
	]);
	const commitSha = (await runGit(input.cwd, ["rev-parse", "--short", "HEAD"])).trim();

	if (!input.options.pr) {
		return { branch, commitSha, pushed: false, prUrl: null };
	}

	await ensureGh();
	const base = input.options.base ?? (await resolveBaseBranch(input.cwd, input.originalBranch));
	await runGit(input.cwd, ["push", "-u", "origin", branch]);

	const args = [
		"pr",
		"create",
		"--base",
		base,
		"--head",
		branch,
		"--title",
		input.options.prTitle ?? input.options.commitMessage,
		"--body",
		buildPrBody(input),
	];
	if (!input.options.ready) args.push("--draft");

	const pr = await runSubprocess("gh", args, { cwd: input.cwd, timeout: 90_000 });
	if (pr.exitCode !== 0) {
		throw new Error(pr.stderr || pr.stdout || "Failed to create pull request with gh.");
	}
	return { branch, commitSha, pushed: true, prUrl: pr.stdout.trim() || null };
};
