import fs from "node:fs";
import path from "node:path";

const AUTO_GENERATED_PATTERNS = [
	/auto-generated/i,
	/@generated/i,
	/DO NOT (?:EDIT|MODIFY)/i,
	/this file (?:is|was) (?:auto-?)?generated/i,
	/automatically generated/i,
	/generated by/i,
];

const GENERATED_ARTIFACT_FILE_PATTERNS = [
	/\.min\.(?:js|css|mjs|cjs)$/i,
	/\.bundle\.(?:js|css|mjs|cjs)$/i,
	/(?:^|\/)\.pnp(?:\.loader)?\.[mc]?js$/i,
];

export const isGeneratedArtifactFile = (filePath: string): boolean =>
	GENERATED_ARTIFACT_FILE_PATTERNS.some((pattern) => pattern.test(filePath));

export const isAutoGenerated = (filePath: string): boolean => {
	const lower = filePath.split(path.sep).join("/").toLowerCase();
	if (
		/(?:^|\/)(?:generated|__generated__|auto-generated|metadata\/generated|client-sdk\/.*\/generated|src-tauri\/gen)\//.test(
			lower,
		)
	) {
		return true;
	}

	let descriptor: number | undefined;
	try {
		descriptor = fs.openSync(filePath, "r");
		const buffer = Buffer.alloc(512);
		const bytesRead = fs.readSync(descriptor, buffer, 0, 512, 0);
		const header = buffer.toString("utf-8", 0, bytesRead);
		if (AUTO_GENERATED_PATTERNS.some((pattern) => pattern.test(header))) return true;
		return /@generated|generated by|do not edit|autogenerated/i.test(header);
	} catch {
		return false;
	} finally {
		if (descriptor !== undefined) {
			fs.closeSync(descriptor);
		}
	}
};
